### ISSUE TITLE
Redirects in Middleware.before don't actually redirect the request

### ISSUE THREAD

**Issue by aisola** [MasoniteFramework/core#113]
Noticed this while making a middleware for my application.

Take the default authentication middleware provided by `craft auth`.

```
class AuthenticationMiddleware:
    ''' Middleware To Check If The User Is Logged In '''

    def __init__(self, Request):
        ''' Inject Any Dependencies From The Service Container '''
        self.request = Request

    def before(self):
        ''' Run This Middleware Before The Route Executes '''
        if not self.request.user():
            self.request.redirectTo('login')

    def after(self):
        ''' Run This Middleware After The Route Executes '''
        pass
```

I expect this middleware to redirect the request if the user is not logged in. As it turns out, the only reason why the `HomeController` redirects with no logged in user is because `HomeController.show` includes:

```
if not Auth(Request).user():                                                                               
            Request.redirect('/login')
```

**Comment by josephmancuso** [comment]
Oh interesting. I'll take a long at this in a few

**Comment by aisola** [comment]
I think that (for some reason) it's not setting `Request.redirect_url` because if I check that value in the controller it shows as `False`.
