### ISSUE TITLE
TypeError > encoding without a string argument

### ISSUE THREAD

**Issue by josephmancuso** [MasoniteFramework/core#123]
This error is a little ambiguous and might not be automatically apparent to the developer what happened.

We need a more obvious error thrown when or before converting the response to bytes. To mimic this error you can just not return something in the view:

```python
def show(self):
    view('index')
```

What this error throws is that we have to convert the response to bytes but the response should be a string (but we didn't return anything.)

This exception might be better off as something like:

`ResponseError - an acceptable response type was not returned.`

Even this seems a little ambiguous. As always, any and all opinions are appreciated

**Comment by aisola** [comment]
I've been pondering this error as well. I can't think of a better way to phrase it, so that exception looks good to me.
