### ISSUE TITLE
Make Pipenv or Poetry the default dependency manager for Masonite

### ISSUE THREAD

**Issue by josephmancuso** [MasoniteFramework/core#132]
This will be for Masonite 2.

This will involve:

- [ ] Deleting the requirements.txt file completely from the masonite repo
- [ ] Remove the Procfile 
Not that this has anything to do with dep management but might as well while we are removing files.
- [x] Add waitress as a dependency to Masonite.
This was already done
- [ ] Test with pipenv instead

So after experimenting, it seems like pipenv is not a direct replace for core developing with masonite yet. Apparently the `-e .` command is still shaky and I can't seem to get it to work correctly. At least the behavior is not the same as pip. 

pipenv is a much better dependency manager than pip and is very similar to composer for PHP. I think it will be an awesome addition to Masonite and we can even specify dev dependencies like waitress.

This will require masonite to come with a Pipfile.lock file in default installations.

**Comment by josephmancuso** [comment]
After more experimenting, this can actually be fully backwards compatible with 1.6

**Comment by josephmancuso** [comment]
I think we should push this into 1.6 which will support the normal pip commands and then remove pip support entirely in 2.0. Pipenv is deff the future of dependency management for Python and it might be good to force that on to developers, especially because it takes 5 minutes to learn and adds a crap ton of reliability and security, especially with its built in `check` commands to check for vulnerabilities in the project.

This also has a new `pipenv shell` command which allows us to activate the virtual environment quite nicely using subprocess

With that being said, it is only recommend when building applications and is explicitly said that it should not be used for libraries that target multiple versions of Python.

**Comment by josephmancuso** [comment]
nvm. I keep going back and forth with this but I realized there needs to be file changes so this will need to go into 2.0 and not 1.6 :(

**Comment by josephmancuso** [comment]
ok again, I think Poetry should be looked into. It's gotten traction in the Python community and there is quite a bit of controversy over pipenv vs poetry and poetry also handles package development as well so we would be able to use Poetry exclusively instead of using Pipenv for Masonite and pip for package development.

**Comment by aisola** [comment]
I agree. I would prefer poetry. It seems to me that it has a better interface.

**Comment by josephmancuso** [comment]
so after some testing with poetry, apparently the `cffi` library needs to be installed but it seems to only be poetry dependent. If I install with normal pip, it works fine, If I install with poetry it breaks. If I add cffi as a dependency in the `pyproject.toml` file it works. Strange

**Comment by josephmancuso** [comment]
ok so there is a little snag here .. I like poetry a lot but the problem I foresee is that currently the install command is inside the craft repo. This might be a problem because different versions may require different installation procedures so the install command should really be inside this repo and inside the masonite package itself.

Now the problem I'm encountering is the virtual environment. With pipenv, I was able to just do craft new and if I subprocess the `pipenv shell` command I was able to activate the virtual environment and run all commands in there. Which means I was able to the Masonite installation steps down to 1 command: `craft new`. With Poetry, I'm not able to activate a virtual environment. so the installation steps would be:

* craft new project
* cd project
* python3 -m venv venv
* source venv/bin/activate
* craft install 
* craft serve

I think this is really annoying. With pipenv I was able to do:

* craft new
* craft serve

But I can't activate a virtual environment so the venv step has to be done..

**Comment by clsource** [comment]
I successfully used pipenv with craft. As pipenv is just a wrapper to pip and virtualenv.

And pipenv support using requirements.txt https://docs.pipenv.org/basics/#importing-from-requirements-txt

The steps was first execute pipenv shell and the use craft install. 

Maybe a simple shell script would be enough to using pipenv. :)

**Comment by josephmancuso** [comment]
yeah craft did have support for pipenv for a while but it has since been removed. How it basically worked was that if pipenv was installed then `craft new` would literally do the whole installation process which was awesome. 

I'm not entirely sure if we should pick one or the other since developers should be able to pick whichever one they like and integrate it but i am leaning more towards pipenv. Having a Pipfile and a Pipfile.lock from the getgo on new 2.1 installation might be the way to go

**Comment by josephmancuso** [comment]
this is completed

**Comment by gloc-mike** [comment]
I have done A LOT of reading recently regarding python packaging and it looks like pipenv is NOT the officially recommended package manager -- just one of a bunch of possibilities -- flit, hatch, poetry, etc.. This article (http://www.pybloggers.com/2018/07/pipenv-promises-a-lot-delivers-very-little/) makes a compelling argument to stick with the status quo i.e. pip; venv (or the like); requirements.txt; etc. You might be wise to abandon (as it looks like you already have) the process of re-adding support. This article also is a very good presentation on the topic (https://sedimental.org/the_packaging_gradient.html). Have read either article previously?

**Comment by josephmancuso** [comment]
i haven't read the article previously, no. And yeah by no means is it actually the "official" one. It was originally advertised that way but ... its just advertising ... doesn't mean its real. just something one dude said.

with that being said I think the overwelming majority of people use pipenv and I think most of the people coming from other python communities will be familiar with it.

but much better is that Python dependency managers are dead simple. They perform a very limited role. Which is awesome because you can just delete the Pipfile and install the pyproject.toml file and you're off to the races.

So although Masonite will come with a Pipfile, replacing it with a pyproject file and using poetry takes less than a minute.

With something like Laravel where composer is deeply connected to the importing / autoloading functionality, Python projects are free of that.

**Comment by vaibhavmule** [comment]
Just mentioning here for fun. 

https://twitter.com/VaibhavMule/status/1039503973277818880
