### ISSUE TITLE
Look into building a logging system 

### ISSUE THREAD

**Issue by josephmancuso** [MasoniteFramework/core#157]
Some errors could be good to throw in a logging system. This should inherit from something like `LoggingContract` which can be used to fetch all classes that inherit the Logging Contract and then log errors where it wants them to be logged.

**Comment by josephmancuso** [comment]
This could even be made into a third party package that ships with Masonite by default

**Comment by clsource** [comment]
Ratlog is a slim and cool way to create logs https://pypi.org/project/ratlog/

**Comment by josephmancuso** [comment]
hm that does look really simple. We just need a wrapper around it to create a common logging system across various logging drivers

**Comment by josephmancuso** [comment]
oh idk why i never saw this. I found an open email about this. Yeah for sure. 2.1 will come with the events package out of the box. so we can deff use the events package for this.

**Comment by clsource** [comment]
I think a good event naming convention is
`masonite:subject.action.state`

with states like

`before`
`init`
`ready`
`after`

So in the log system maybe like

`masonite:log.write.ready`

**Comment by josephmancuso** [comment]
🤔 hmm. let me take a look at how other frameworks do it. That seems to long for me.

**Comment by josephmancuso** [comment]
we also have the option to listen for class based events. Maybe we should do something like:

```
from masonite.events import ViewRendered
from app.events import SubscribeUser

event.listen(ViewRendered, [SubsribeUser])
```


Something like that. So instead of `masonite:log.write.ready` it would be:

```
from masonite.events import LogWrite
```

and we would listen to the class

**Comment by josephmancuso** [comment]
events package is actually kind of cool https://docs.masoniteproject.com/useful-features/events

**Comment by clsource** [comment]
Yeah that sounds super cool.
in that way is easier to pass params required in logs like
the filename 👍

**Comment by clsource** [comment]
this loggin framework seems nice https://github.com/BNMetrics/logme 👍

**Comment by nioperas06** [comment]
Definitely, need to know what's happening within my application... log messages to files 🤔
