### ISSUE TITLE
Add template caching support

### ISSUE THREAD

**Issue by josephmancuso** [MasoniteFramework/core#19]
sometimes views don't need to be loaded over and over again and can just be rendered from a cache. I should be able to cache on a per template basis. Maybe something like:

```python
def show(self):
    view('welcome').cache() # cache forever
    view('welcome').cache_for(5, 'minutes')
    view('welcome').cache_for(5, 'hours')
    view('welcome').cache_for(5, 'days')
    view('welcome').cache_for(5, 'months')
    view('welcome').cache_for(5, 'years')
```

This should ignore the template rendering entirely and just show the already rendered cached template

**Comment by josephmancuso** [comment]
This is going to be a highly used feature. many times you will want to cache a specific route so you're not constantly looping through foreach inside foreach.

We'll need to make this really simple and follow the Manager - Driver Pattern like before.

So we'll need to create a `CacheManager` and a `CacheDiskDriver` so other people can make other caching drivers (like redis, google caching or whatever else there is out there).

Then inside the `View` [class here](https://github.com/MasoniteFramework/core/blob/master/masonite/view.py#L13) that `render()` method will return the rendered template. 

We might have to rearrange it a bit but we need the Service Container inside this view so we can retrieve the `CacheManager` from the container. Take a look at this `ViewProvider` [here](https://github.com/MasoniteFramework/core/blob/master/masonite/providers/ViewProvider.py)

so we'll then cache the rendered template inside the `bootstrap/cache` directory (you'll have to make this).

the name of the rendered template should be something like: `name.of.template:193827182.html`

so the first half will be the name of the template as usual as the second half will be a timestamp.

The pseudo code will look something like:

1. render the template
2. if the cache is set, cache the template at: `bootstrap/cache/views/name.of.view:1928382921.html`
2a. The timestamp will comes from: now + 5 minutes if the user has set the cache_for(5, 'minutes') etc etc
3. Next time the template is going to be rendered, check if the template exists *and* the timestamp is still in the future
3a. if it is then show the cached template instead of rendering the template
3b. if not then render the template as usual

The key here is to create a `CacheManager` though we can use to cache things to the disk.

**Comment by josephmancuso** [comment]
You can read about [creating managers here](https://masoniteframework.gitbooks.io/docs/content/managers-and-drivers/about-managers.html)

**Comment by mapeveri** [comment]
I understood well?:

First render the view, then check if the cache is set, if so, I record it in bootstrap / cache and verify the time (here I do not understand how to verify it), if it is in the range I take it from the cache, but if not I return to render and do the whole process. It is right?

**Comment by josephmancuso** [comment]
Close. Just check for the cached template first. The `View` class should look something along the lines of:

```python
class View(object):

    def __init__(self, Cache):
        self.dictionary = {}
        self.composers = {}
        self.env = Environment(
            loader=PackageLoader('resources', 'templates'),
            autoescape=select_autoescape(['html', 'xml'])
        )
        self.cache_manager = Cache
        self.cache=False
        self.cache_time=None
        self.cache_type=None

    def cache(self, time, type):
        self.cache = True
        self.cache_time = time
        self.cache_type = type
        return self

    def render(self, template, dictionary = {}):
        
        if cached_template_exists():
            return the cached template

        self.dictionary.update(dictionary)
        
        if template in self.composers:
            self.dictionary.update(self.composers[template])
        
        if '*' in self.composers:
            self.dictionary.update(self.composers['*'])

        return self.env.get_template(template + '.html').render(self.dictionary)
```
