### ISSUE TITLE
Craft install with No Key

### ISSUE THREAD

**Issue by josephmancuso** [MasoniteFramework/core#194]
Craft install should have a --no-key flag on it so we can run something like:

```
$ craft install --no-key
```

Which will simply run the craft install but will not generate and store a new key. This command should typically be ran when installing your application as a team (since you may be sharing the same secret key for development reasons). Or it may be ran when deploying your application to something like Heroku and be apart of your deployment script.

All the logic needed to finish this ticket is in the `MasoniteFramework/craft` repo inside the `InstallCommand`. This just requires wrapping some logic around the `craft key --store` line of code.

**Comment by nioperas06** [comment]
Okay, I take this one ✋
