### ISSUE TITLE
add a way for multiple "has" checks

### ISSUE THREAD

**Issue by josephmancuso** [MasoniteFramework/core#198]
We currently have a way to check if an input exists:

```python
if request.has('csrf_token'):
    # do some logic
```

but what if we need to see if there are multiple? maybe a `csrf_token` and an `email` present?

We should be able to do this in that case:

```python
if request.has('csrf_token', 'email'):
    # do some logic
```

this should only return true if `csrf_token` AND `email` are both in the input.

#202

**Comment by nioperas06** [comment]
I'll work on this!

**Comment by josephmancuso** [comment]
👍 😄 
All yours
