### ISSUE TITLE
MySQL error in craft install

### ISSUE THREAD

**Issue by mapeveri** [MasoniteFramework/core#20]
Hi i want test this framework, but when run craft install command, display this error:

![image](https://user-images.githubusercontent.com/6276555/36568678-a4fa2530-1809-11e8-83ee-830fda529ea1.png)

I do not use mysql (postgresql use) I force myself to install it.

```
sudo apt-get install mysql-server
sudo apt-get install libmysqlclient-dev
```

I should not or in any case ask me.

Regards!

**Comment by josephmancuso** [comment]
You're running linux correct? Which flavor?

**Comment by mapeveri** [comment]
Yes, ubuntu 16.04.

**Comment by josephmancuso** [comment]
ok great and running those two commands fixed it right?

**Comment by mapeveri** [comment]
Yes, with these commands, it was resolved. In my case, I wanted to test the framework with PostgreSQL. Now I'm playing with him, I like him a lot.

**Comment by josephmancuso** [comment]
Thank you. I'll run some tests on linux. I appreciate the issue!

**Comment by mapeveri** [comment]
You're welcome, I'd like to contribute to the project, I do not know if I can help something? Is there a gitter or something for style to chat?

**Comment by josephmancuso** [comment]
Sure. There is a [How To Contribute](https://masoniteframework.gitbooks.io/docs/content/how-to-contribute.html) guide in the documentation and the [Gitter.im](https://gitter.im/masonite-framework/Lobby) chatroom

**Comment by mapeveri** [comment]
Great!

**Comment by josephmancuso** [comment]
Added requirement in the installation documentation for the `python-dev` and the `libmysqlclient-dev` libraries to be installed before installing masonite

**Comment by mapeveri** [comment]
About this, I think it would be best to add a question, do not you think? For example, if I want to use PostgreSQL, why would I have to install MySQL?

**Comment by josephmancuso** [comment]
Ok so we're going to switch to the PyMySQL requirement which doesn't require installing mysql on the server.

**Comment by mapeveri** [comment]
Awesome!

**Comment by josephmancuso** [comment]
This will be in the new 1.4 release e9889fcef08463e4f09bd61472fceaa7a6f8c835
