### ISSUE TITLE
Add several new Helper methods

### ISSUE THREAD

**Issue by josephmancuso** [MasoniteFramework/core#204]
I'm a pretty big fan of helper methods but some developers think it's too magical. The framework does not require people use them so they are just there for mocking things up quickly. In this issue will be several helper functions that should be added. These can be added into new minor version releases:

* mail helper
* log helper (requires logging package to be built)
* flash - short for `request.session.flash()`

**Comment by mitchdennett** [comment]
What were you envisioning for the mail helper method? I want to get my feet wet and maybe start contributing.

**Comment by josephmancuso** [comment]
write now to do mail it is something like:

```python
def show(self, Mail):
    Mail.to(User.find(1)) \
        .subject('subject here') \
        .template('mail/user') \
        .send()
```

Most of these builtin helpers can be called with something like this:

```python
def show(self):
    mail().to(User.find(1)) \
        .subject('subject here') \
        .template('mail/user') \
        .send()
```

notice no imports, no resolving. It just works. Examples can be found in the `HelpersProvider` in core. It usually works better with things like the request class:

```python
def show(self):
    request().input('here')
```

notice again no imports. If you want to find a random method that is used often in the codebase and just make a helper out of it using the the examples in `HelpersProvider` that would be a really simple contribution

**Comment by mitchdennett** [comment]
So should I take a stab at making a Mail Helper. Or has someone already done that?

**Comment by vaibhavmule** [comment]
What does `request.session.flash()` suppose to do ?

**Comment by josephmancuso** [comment]
Saves data to a session but only for the next request. This is useful for things like error messages that you don’t want to save for more than 1 request

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by vaibhavmule** [comment]
Ok, Let me contribute for `flash`, how is ts supposed to work?

**Comment by josephmancuso** [comment]
@vaibhavmule check the code for the request.session.flash() code and just make a helper function out of it in the `HelpersProvider` using similiar syntax
