### ISSUE TITLE
Create a craft "share" command 

### ISSUE THREAD

**Issue by josephmancuso** [MasoniteFramework/core#205]
This command should simply be a wrapper around the NGROK cli tool and should throw an error if NGROK is not installed

This command should look something like:

```
$ craft share
```

which will fire up an NGROK tunnel to your application

**Comment by nioperas06** [comment]
I will work on this but the craft repo does not have any tests 😕. If we do not need it, it suits me too 😁.

**Comment by josephmancuso** [comment]
No currently no tests. Just manual testing for now

**Comment by josephmancuso** [comment]
actually thinking about this more. This command shouldn't go into craft. it should go here. Just because the information we use to share the application may be version specific. Also you can't share an application if there is no application so this command should only be available via a Masonite application

**Comment by nioperas06** [comment]
Sounds good. 👍

**Comment by nioperas06** [comment]
So, how do you test commands available inside a Masonite application?

**Comment by nioperas06** [comment]
I mean in development.

**Comment by josephmancuso** [comment]
So this is slightly tricky. I still have to find a better way to do this but what you can do is the core repo has several folders named the same as a masonite app. It has app, config, databases, resources etc. 

so what you need to do if you want to do development is actually rename the folders in the core repo on your machine. I usually name them _app, _config etc.

once that is done I will go my masonite application and activate my virtual environment via the command line. Then while inside my virtual environment I will navigate inside my terminal to where core is installed.

once I am at the core repo and my masonite application virtual environment is activated, I will run:

    pip uninstall masonite
    pip install -e .

That will uninstall masonite and install the core repo as editable so i can make changes live

**Comment by josephmancuso** [comment]
Does that all make sense? It's a bit of a work around. I'll need to find a better way to do this but it's a limitation of pip. For some reason they install ALL the folders and not just the modules specified in the setup.py file.

**Comment by nioperas06** [comment]
Okay, I'll try doing this. 👍

**Comment by josephmancuso** [comment]
When you create the ngrok tunnel, it should use the SITE environment config inside config/application.py

**Comment by josephmancuso** [comment]
doesn;t really make sense after implementing this
