### ISSUE TITLE
Add accepted file types to upload drivers

### ISSUE THREAD

**Issue by josephmancuso** [MasoniteFramework/core#22]
There needs to be a way to accept specific file types. The end state of the code should look something like:

```python
def show(self, Upload):
    Upload.accept('png', 'jpg').store(request().input(file))
```

You may have to abstract this and make a BaseUploadDriver which contains this accept method and just make sure it works on the two drivers by inheriting from them. It should be really simple and should just be a check if the filetype is inside the list

Let me know if anyone has any additional questions

**Comment by mapeveri** [comment]
Take this issue, I almost have the development, but I do not know how to write the test. I have this:

```
def test_upload_manage_limit_files():
    container = App()

    container.bind('StorageConfig', storage)
    container.bind('UploadDiskDriver', UploadDiskDriver)
```


How can i access to Upload?.

**Comment by josephmancuso** [comment]
Sure so the driver already has that store method. The `request().input()` file is an image that is uploaded by the form. In Masonite, there are a few helper functions here that the user can use after the `HelpersProvider` is ran. Don't worry about the `request()` function for testing though. The `request()` function is the same as doing `container.make('Request')`. So it needs a request object. There are 2 ways to mock the container.

## Option 1 - Use the Masonite TestSuite to create a mock container

The testsuite isn't complete yet but it has some good functionality. To use it is simple and an example of a test that uses the [test suite can be found here](https://github.com/MasoniteFramework/core/blob/6c3ef45c0c1bad14b70ac318e924adbf2fd9a871/tests/queues/test_redis_driver.py#L9)

## Option 2 - Simply bind a request object into the container

An example of that can be [found here between lines 4 and 34](https://github.com/MasoniteFramework/core/blob/38530ad16669b9cc38719fa18d1e1370a3b885aa/tests/test_routes.py)

That's how you create a request object BUT for this purpose all you really need is an image because that's what the `request().input()` actually returns so try to test this out:

https://stackoverflow.com/questions/45087638/get-image-filename-from-image-pil

**Comment by mapeveri** [comment]
I set the path from my disk? It's ok?. For example:

UploadManager(container).driver('disk').accept('jpg', 'png').store(PATH + '/test.png')

??

I have other question, how can access to file from method 'accept' for check is one extension valid?.

My class is:

```
class BaseUploadDriver(object):
    """
    Class base for upload drivers
    """

    def accept(self, *args, **kwargs):
        print(args)
```

And args return one tuple with ('jpg', 'png',) But I do not have to compare. I'm missing something to understand.

**Comment by josephmancuso** [comment]
yeah check my code above. that should answer your question. If not please let me know and i'll explain further.

**Comment by josephmancuso** [comment]
Inside the constructor you should add:

```python
def __init__(self, ... other stuff ...):
    ...
    self.accept_file_types = None # this will accept all file types
```

**Comment by josephmancuso** [comment]
As for the the image, yes just throw a small test file somewhere in the repository. The code should look like:

`UploadManager(container).driver('disk').accept('jpg', 'png').store(os.path.join(os.getcwd(), 'test.png'))`

**Comment by mapeveri** [comment]
I'm going to try that :)
