### ISSUE TITLE
Move this masonite code into it's own Masonite application.

### ISSUE THREAD

**Issue by josephmancuso** [MasoniteFramework/core#220]
testing sort of came after the fact of several classes so I started to implement things little by little. now there is super weird boiler plate.

The solution here is to simply create a new Masonite application, then take the entire `masonite` folder and plop it on and move over the controllers. Run the tests and get all the tests to pass by carefully copying over things from this repo to the new codebase as needed.

This should be a fairly straight forward implementation.

**Comment by vaibhavmule** [comment]
Shall I take this or Do I need https://github.com/MasoniteFramework/core/pull/260 to merged?

**Comment by vaibhavmule** [comment]
Are we doing this for the `develop` branch or stable one, if it is `develop` then I need to create Masonite application with `craft new foo --branch=develop`

**Comment by josephmancuso** [comment]
yeah you'll need the develop branch

**Comment by josephmancuso** [comment]
let me merge #260 first though since that seems to be having a bunch of conflicts. let me get that out of the way. I can get that merged in prob tomorrow night.

**Comment by vaibhavmule** [comment]
Sure, I was actually about to ask that, this should be only done after that is merge

**Comment by vaibhavmule** [comment]
#260 merged, Can I get started with this?

**Comment by josephmancuso** [comment]
fixed
