### ISSUE TITLE
Add a way to make a class from a container.

### ISSUE THREAD

**Issue by josephmancuso** [MasoniteFramework/core#224]
right now we can do something like:

```python
app.make('Request')
```

but we really should be able to do:

```python
from app.request import Request
app.make(Request)
```

**Comment by theodesp** [comment]
How do you propose to do that in simple steps? We have a dict of keys to values
` self.providers = {}` and we can check if the values match the provided parameter type however this is inefficient

Or we could maintain another mapping of types information so we can search by type which is OK but not great

Or we could enhance the bind method to include more information so we could retrieve by name or by type info but this increases the complexity of the implementation.

**Comment by josephmancuso** [comment]
similiar to how we resolve annotations via the `_find_annotation_parameter` method on the `App` class in `masonite/app.py`.

We do loop through each one which is sort of inefficient. The only more efficient way would be using a better search algorithm instead of an O(1) search it would be a Binary search tree or something so it would be more of a O(logn) search. I think whoever figures out how to make the container a binary search tree would increase the speed of Masonite by like 10x lol. The real speed increases can be worked on via the resolving since that is what is used over and over again in Masonite.
