### ISSUE TITLE
Make password reset functionality along with auth command

### ISSUE THREAD

**Issue by josephmancuso** [MasoniteFramework/core#262]

**Comment by theodesp** [comment]
Is email confirmation included?

**Comment by josephmancuso** [comment]
umm I wonder if could add a toggle for that 🤔 . Maybe something like this:

```
SomeNewControllerWeAreUsing:

    confirmation = False

    def show(self):
        blah blah blah
```

and then we add the logic but just check for the confirmation flag on whether we should actually do it or not? Thoughts? Basically add the logic as if we did have email confirmation but just set that if statement so people can have it off by default. And we can just put in the docs to make it true if they want that? What do you think?

**Comment by theodesp** [comment]
I think we need some sort of confirmation to be sure that the reset code is sent to the right user.

See: 

https://stackoverflow.com/questions/1162829/secure-password-reset-without-sending-an-e-mail
https://www.troyhunt.com/everything-you-ever-wanted-to-know/
https://www.owasp.org/index.php/Forgot_Password_Cheat_Sheet

**Comment by josephmancuso** [comment]
OOH you're talking about the reset code lol. I thought you were talking about the confirmation emails like "click on the link in your email to confirm your email address" or something. Like after the user first signs up not when they reset their password. Umm we could create a new table by default and put the tokens in there.

**Comment by theodesp** [comment]
Cool so it will be a 2-page project first for reset password view and the other for reset password view confirm?

**Comment by josephmancuso** [comment]
yeah probably a view for "enter your email" -> then an email is sent to them -> then they click the email which goes back to the website and you should see 2 input boxes "new password, confirm password" input. Nice and simple views. People will be customizing these so as long as it works and all the logic is there, people can tweak it to their application instead of creating an entirely new one.

**Comment by josephmancuso** [comment]
make sure you base off the `develop` branch and not the `master` branch on the masoniteframework/masonite repo

**Comment by theodesp** [comment]
Ok

**Comment by josephmancuso** [comment]
once you get the controller logic working we can just throw the new controllers in the core repo develop branch and just update the `craft auth` command in `masonite/commands/AuthCommand.py`

**Comment by vaibhavmule** [comment]
Can I take this?

**Comment by josephmancuso** [comment]
sure :)

**Comment by josephmancuso** [comment]
@vaibhavmule any status on this bud? Just checking some open issues

**Comment by vaibhavmule** [comment]
@josephmancuso 

Sorry, let me try to get it done ASAP.

**Comment by josephmancuso** [comment]
completed
