### ISSUE TITLE
Remove the need for the |safe filter on various template tags

### ISSUE THREAD

**Issue by josephmancuso** [MasoniteFramework/core#265]
Currently we have to do things like:

```
{{ csrf_field|safe }}
```

but that's pretty annoying. We should just be able to do:

```
{{ csrf_field}}
```

**Comment by theodesp** [comment]
Can I work on this?

**Comment by josephmancuso** [comment]
it's actually already done #273 😢

**Comment by josephmancuso** [comment]
my fault I should have linked it here. Issue is still open since I haven't yet merged it
