### ISSUE TITLE
Add Python 3.7 to travis.yml file

### ISSUE THREAD

**Issue by josephmancuso** [MasoniteFramework/core#272]
# First Time Contributors ONLY

Just need to base off of the `master` branch and add `- python 3.7` to the `.travis.yml` file.

**Comment by avnish98** [comment]
I would like to work on this one

**Comment by josephmancuso** [comment]
Actually being worked on by @bjorntheart here: https://github.com/MasoniteFramework/core/pull/274

but I don't think Travis natively supports 3.7 like it does other Python versions

**Comment by josephmancuso** [comment]
for some reason we can get 3.7 to be ran in Travis but simply adding 3.7 breaks 3.4 🤔

**Comment by avnish98** [comment]
@josephmancuso Okay, I will also work on issue then
