### ISSUE TITLE
CSRFMiddleware for Masonite Entry API Routes

### ISSUE THREAD

**Issue by mitchdennett** [MasoniteFramework/core#275]
Have CSRFMiddleware run for API Routes and not just Web Routes.

**Comment by josephmancuso** [comment]
note to self: This needs to be an update on the Masonite entry package. Will need to restructure how the API package is done. Possibly removing the usage of resources in it's own structure and simply add it to the normal web routes.

**Comment by josephmancuso** [comment]
moving this from beta 2 to the beta 3 release

**Comment by josephmancuso** [comment]
this is also fixed in the new api package
