### ISSUE TITLE
Make pipenv the officially supported Python package manager

### ISSUE THREAD

**Issue by josephmancuso** [MasoniteFramework/core#276]
For 2.1 we will need a modern python package manager (not pip). The battle has been waging for a while now but I think Pipenv is in the lead over Poetry.

This issue requires you to go to the https://github.com/MasoniteFramework/masonite repository and setup pipenv as the default there.

You'll need to base off of the develop branch there since the master branch is what is currently being used for 2.0 and the develop branch will become the 2.1 release. There have been many changes already on that branch getting ready for 2.1.

the https://github.com/MasoniteFramework/masonite repo is what is actually installed for new applications when `craft new` is ran. It basically downloads the zip file and unpacks it on the users computer.

You can open the PR on the https://github.com/MasoniteFramework/masonite repo.

**Comment by vaibhavmule** [comment]
How can I get started with this if no one is working on it?

I haven't worked with `pipenv` before, but it looks straightforward to me when I saw pipenv's docs. 

Do you want to generate `Pipfile` and `Pipfile.lock` and get rid of `requirements.txt`

**Comment by josephmancuso** [comment]
umm just a Pipfile. The user would generate the lock file when they go to install everything.

And yeah just clone https://github.com/MasoniteFramework/masonite and checkout the `develop` branch on it and then really just go through the installation steps of Pipenv and install Pipenv on that project as if it was a new project for you. Then just make a PR and we can go over it together.
