### ISSUE TITLE
Add adapter for GraphQL

### ISSUE THREAD

**Issue by theodesp** [MasoniteFramework/core#279]
I've recently read this article:
https://medium.freecodecamp.org/how-to-get-instant-graphql-apis-on-your-existing-django-application-c8fcfdb945aa

and I was wowed. I think it will be a good addition to have first class Graphql support or via an adapter

**Comment by josephmancuso** [comment]
this will require creating a driver in the Orator repo. I'd also like to create a sqlserver driver and mongodb driver but just haven't had to time to learn the Orator codebase. It's pretty complex. I'm gonna keep this open for now to remind me to look into it this weekend.

**Comment by josephmancuso** [comment]
once I explore more into the orator code base i'll reopen
