### ISSUE TITLE
Implement Down for Maintenance Mode

### ISSUE THREAD

**Issue by theodesp** [MasoniteFramework/core#282]
It would be useful to provide this functionality:

https://laravel.com/docs/5.7/configuration#maintenance-mode

**Comment by josephmancuso** [comment]
what do you think the best way to do it is on an ehemeral system like Heroku?

I believe how Laravel does it is they create a random file called `down` and check for that but on something like Heroku, we can't. Heroku has it's own maintencance mode so it's fine but it uses it's own "splash screen".

**Comment by theodesp** [comment]
Maybe we can detect for an ephemeral file system or maybe a specialized check for Heroku environment (or something similar and not specific to Heroku) and ignore the command.

**Comment by josephmancuso** [comment]
Note to self this weekend:

Let's make a `down` file inside the `bootstrap` filesystem and a middleware that will throw a `503` error if that file exists. When `craft up` is ran then we can just remove that file

**Comment by josephmancuso** [comment]
The docs should have a good section on middleware. Let me know if there isn’t any good references there for it

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by josephmancuso** [comment]
this is fixed
