### ISSUE TITLE
SMTP Driver doesn't work when SSL is required

### ISSUE THREAD

**Issue by mitchdennett** [MasoniteFramework/core#288]
I use Amazon Workmail and the SMTP settings require SSL. 

Using smtplib.SMTP() gives `Connection unexpectedly closed` error

In MailSmtpdriver.py
Changing: 
`s = smtplib.SMTP('{0}:{1}'.format(config['host'], config['port']))`

To:
`s = smtplib.SMTP_SSL('{0}:{1}'.format(config['host'], config['port']))`

Fixes this issue. 
Do we want to create another driver or provide a config option?

**Comment by josephmancuso** [comment]
nah what we could do is something like:

```python
if 'https' in config['host']:
    s = smtplib.SMTP_SSL('{0}:{1}'.format(config['host'], config['port']))
else:
    s = smtplib.SMTP('{0}:{1}'.format(config['host'], config['port']))
```

right? This way if it is trying to connect with ssl it will work, right? Or is it still connecting to `http`? What does the host look like?

**Comment by mitchdennett** [comment]
My host is smtp.mail.us-west-2.awsapps.com. So you don’t pretend https

**Comment by josephmancuso** [comment]
ah ok. Yeah so we'll have to add a config option to the `smtp` driver like this:

```python
    'smtp': {
        'host': os.getenv('MAIL_HOST', 'smtp.mailtrap.io'),
        'port': os.getenv('MAIL_PORT', '465'),
        'username': os.getenv('MAIL_USERNAME', 'username'),
        'password': os.getenv('MAIL_PASSWORD', 'password'),
        'ssl': True,
    },
```

**Comment by mitchdennett** [comment]
Yeah that would work. In doing a bit of research it looks like port 465 is used for SMTPS (SSL). So could possibly base it off the port number but I’m not 100% sure that that is the case every time.

**Comment by josephmancuso** [comment]
eh i'd rather be explicit about it

**Comment by vaibhavmule** [comment]
Can I work on this?

**Comment by josephmancuso** [comment]
Sure 😄 let me know if you have any questions

**Comment by vaibhavmule** [comment]
@josephmancuso I ran tests for both the cases when ssl is true and false, it was good.
