### ISSUE TITLE
add contracts

### ISSUE THREAD

**Issue by josephmancuso** [MasoniteFramework/core#29]
contracts are a great way to ensure that a class has all the methods it needs. This is very similar to a interface in other languages but Python doesn't have traditional interfaces. We can do something like:

```python
class UploadDriverContract(object):
    
    def store(): raise NotImplemented()

    def store_as(): raise NotImplemented()

    def another_method(): raise NotImplemented()
```

then all drivers need to inherit from this:

```python
from masonite.contracts import UploadDriverContract

class UploadGoogleDriver(UploadDriverContract):
    pass
```

Now anytime anyone creates a driver they will have a minimum amount of methods necessary required

Masonite drivers need to program to an interface and not an implementation

**Comment by josephmancuso** [comment]
@mapeveri

**Comment by josephmancuso** [comment]
actually this will probably need to use the `abc` module

**Comment by mapeveri** [comment]
It can be done with the abc module, it is a good option, but we can also put the default code to the main class and then each driver simply overrides it. Either of the two options I see them well.
