### ISSUE TITLE
Remove the redundant coveralls reporting on every single python version

### ISSUE THREAD

**Issue by josephmancuso** [MasoniteFramework/core#291]
You may have noticed that coveralls comments like 3 or 4 times on a pull request reporting the coverage. This is because it is set to report on every successful build in the travis.yml file. We need to pick 1 python version and only report for that

**Comment by vaibhavmule** [comment]
I can work on this, let me see how this can be done and what python version are we using?

**Comment by josephmancuso** [comment]
umm let's go with 3.6

**Comment by josephmancuso** [comment]
base off of master as well

**Comment by vaibhavmule** [comment]
@josephmancuso That's better or we better have this mentioned on contribution guide.
