### ISSUE TITLE
Why is not router just show same content for '/blog/' and '/blog'?

### ISSUE THREAD

**Issue by vaibhavmule** [MasoniteFramework/core#292]
I have followed tutorial about creating a blog in `masonite`,  I wrote a route which points to `/blog` but when I visit `/blog/` it does not return the same. 
if it is not implemented, I would suggest this to have in masonite as [usually trailing slash and non-trailing slash URLs often serve the same content and it just that you have to have preferred version](https://webmasters.googleblog.com/2010/04/to-slash-or-not-to-slash.html)

**Comment by josephmancuso** [comment]
that's expected behavior. Actually it's so expected there is extra code to ensure this works as is lol. But we can remove that. Makes sense to me :)

**Comment by vaibhavmule** [comment]
As I can see, most of the framework render same on with or without trailing slash. I have got it working with following code. 

```
    if route.route_url.endswith('/'):
        if router.url.endswith('/'):
            matchurl = re.compile(regex.replace(r'\/\/$', r'\/$'))
        else:
            matchurl = re.compile(regex.replace(r'\/\/$', r'$'))
    else:
        if router.url.endswith('/'):
            matchurl = re.compile(regex)
        else:
            matchurl = re.compile(regex.replace(r'\/$', r'$'))
```

**Comment by josephmancuso** [comment]
yeah i'm a fan of changing it

**Comment by vaibhavmule** [comment]
If that make sense, I can male PR for it.

**Comment by josephmancuso** [comment]
yeah go for it. make sure there is a corresponding test for it. We might be able to refactor to get the logic down a bit

**Comment by vaibhavmule** [comment]
Sure, will write a test and do PR and refactoring can happen on PR review may be.

**Comment by josephmancuso** [comment]
fixed
