### ISSUE TITLE
craft middleware MiddlewareName : Create a new middleware

### ISSUE THREAD

**Issue by nioperas06** [MasoniteFramework/core#293]

**Comment by vaibhavmule** [comment]
as #245 is done, Can I take this?

**Comment by josephmancuso** [comment]
go for it :)

**Comment by josephmancuso** [comment]
should be really simple with the new template based scaffold commands

**Comment by vaibhavmule** [comment]
I liked what you have done there, good version of scaffolding.

**Comment by josephmancuso** [comment]
fixed
