### ISSUE TITLE
Starting a Masonite project in a existing directory

### ISSUE THREAD

**Issue by nioperas06** [MasoniteFramework/core#295]
I would like to initializing a new Masonite project like this
```
$ mkdir my_app
$ pipenv install --three
$ pipenv shell
$ pipenv install masonite-cli
$ craft new my_app .
```

**Comment by vaibhavmule** [comment]
but a `.` can be an absolute path?

**Comment by josephmancuso** [comment]
usually it’s designated for the current directory but maybe it’s also a good idea to also have the ability to specify a path as well

**Comment by vaibhavmule** [comment]
@josephmancuso if it a case for an only current directory, where should we unzip the repo?

Currently, it unzips in `os.cwd` and then rename it

I was trying with the same code, I got a Directory not empty error.

https://stackoverflow.com/questions/52234073/python-os-rename-directory-not-empty

**Comment by josephmancuso** [comment]
🤔 might have to somehow move all the contents of the directory into the current directory maybe? Maybe some `shutil` module can do that

**Comment by vaibhavmule** [comment]
@josephmancuso  I haven't tried `shutil` but let me see.

**Comment by vaibhavmule** [comment]
The feature is available in `masonite-cli==2.0.12`

**Comment by nioperas06** [comment]
Hey @vaibhavmule This feature does not work properly for a while.

Steps to reproduce
```
$ mkdir my_app
$ cd my_app
$ pipenv install --three
$ pipenv shell
$ pipenv install masonite-cli
$ craft new my_app .
$ craft install
$ craft serve
[CommandNotFound]                
  Command "serve" is not defined.
```

**Comment by josephmancuso** [comment]
pipenv install steps are different than normal installing. craft will install from a Pipfile if one exists. With your steps, it won't install masonite since thats in the requirement.txt file.

The correct steps when using pipenv is this:

```
$ mkdir my_app
$ cd my_app
$ pipenv install --three
$ pipenv shell
$ pipenv install masonite-cli masonite
$ craft new my_app .
$ craft install
$ craft serve
```

Notice the addition of installing Masonite with pipenv first. Since now that is in the lock file, craft install at this point only creates the .env file

**Comment by josephmancuso** [comment]
You can see it in video form since I used pipenv for the CFE 2.1 tutorial series on Youtube

**Comment by nioperas06** [comment]
Watching... :+1:
