### ISSUE TITLE
add slack link to welcome page of Masonite

### ISSUE THREAD

**Issue by vaibhavmule** [MasoniteFramework/core#299]
I suggest adding slask, twitter and logo to welcome page. here is a 
![masonite 2 0](https://user-images.githubusercontent.com/6290791/45253960-f6127c00-b38c-11e8-99cd-9119c05d9e0a.png)
screenshot, this is how it would look like.

**Comment by josephmancuso** [comment]
I'm gonna keep this open for now as a remember to do this before beta 3 but we'll need to find a developer to make a new homepage. We have a few submissions already

**Comment by vaibhavmule** [comment]
Oh really, we already have a submission, I would love to see.

**Comment by josephmancuso** [comment]
[masonite (2).zip](https://github.com/MasoniteFramework/core/files/2363533/masonite.2.zip)

**Comment by vaibhavmule** [comment]
Please consider adding a slack link for beta 2, as it will help more users to come on Slack. 
just a thought.

**Comment by josephmancuso** [comment]
This is completed for now. There may be changes the welcome page though
