### ISSUE TITLE
add CONTRIBUTING.md

### ISSUE THREAD

**Issue by vaibhavmule** [MasoniteFramework/core#301]
Docs: https://help.github.com/articles/setting-guidelines-for-repository-contributors/

Examples of contribution guidelines

The Atom editor [contribution guidelines.](https://github.com/atom/atom/blob/master/CONTRIBUTING.md)
The Ruby on Rails [contribution guidelines](https://github.com/rails/rails/blob/master/CONTRIBUTING.md).
The Open Government [contribution guidelines](https://github.com/opengovernment/opengovernment/blob/master/CONTRIBUTING.md).

**Comment by josephmancuso** [comment]
This one should be fairly simple, just need to convert https://docs.masoniteproject.com/prologue/contributing-guide into markdown and make a CONTRIBUTING.md file

**Comment by vaibhavmule** [comment]
Closing it as PR is merged.
