### ISSUE TITLE
add craft db:create command

### ISSUE THREAD

**Issue by vaibhavmule** [MasoniteFramework/core#303]
This command will create a database based on `masonite/config/database.py`

Reference: 
`mix ecto.create` from [Phoenix Framework](https://hexdocs.pm/phoenix/up_and_running.html#content)
`rake db:create` from [Rails Framework](https://guides.rubyonrails.org/v3.2/getting_started.html)

**Comment by nioperas06** [comment]
I'll work on this 👍

**Comment by josephmancuso** [comment]
awesome :) Should be some lower level Orator methods you can use

**Comment by vaibhavmule** [comment]
Just want to tell you,

We should also add `craft db:drop` too.

**Comment by josephmancuso** [comment]
I don't think this is possible by default in Orator? What are your guy's solutions / thoughts on this?

**Comment by vaibhavmule** [comment]
Just a thought,

What need to be done here is to create command out of what mentioned in
orator's Makefile for create-db.

**Comment by josephmancuso** [comment]
oh true

**Comment by vaibhavmule** [comment]
Yeah, but better if it is created in orator as Masonite doesn't need worry about those command.

**Comment by nioperas06** [comment]
Absolutely, it would be better if it were possible in Orator.

**Comment by nioperas06** [comment]
Something like: `orator create:db -c config/database.py`

**Comment by josephmancuso** [comment]
going to remove this issue for now. It's a bit stale. if anyone wants to work on it then go for it but it's not a huge priority
