### ISSUE TITLE
Need more public showcases

### ISSUE THREAD

**Issue by theodesp** [MasoniteFramework/core#313]
We need more exposure with public examples of usage 
For example, we need to be listed here:

- [x] http://www.todobackend.com/
- [x] https://www.slant.co/
- [x] https://github.com/the-benchmarker/web-frameworks/issues/1238
- [x] https://stackshare.io/ 
- [ ] https://github.com/gothinkster/realworld (in progress by @vaibhavmule )
- [x] [Awesome Python](https://github.com/vinta/awesome-python/pull/1028)

Maybe a checkbox of subtasks for each item so we can have more people working on it

**Comment by josephmancuso** [comment]
Made a checklist out of the first comment. If anyone can get it on any of these services I will check them off.

**Comment by vaibhavmule** [comment]
I have tried adding `Masonite` in `slant.co` but I'm not sure if it is added or added to the specific question.

**Comment by josephmancuso** [comment]
awesome :)

**Comment by vaibhavmule** [comment]
- [Add Masonite](https://github.com/up-for-grabs/up-for-grabs.net/pull/997) to [Up For Grabs
](https://up-for-grabs.net)
- Created [Awesome Masonite](https://github.com/vaibhavmule/awesome-masonite) which can be added to [Aweomse List](https://github.com/sindresorhus/awesome#readme)

**Comment by rickwest** [comment]
I've created a PR to add Masonite to Python Guide https://github.com/realpython/python-guide/pull/922 :)

**Comment by vaibhavmule** [comment]
Just want to update that I'm working on gothinkster's realworld example, https://github.com/gothinkster/realworld/issues/304 here is PR and is repo: https://github.com/vaibhavmule/masonite-realworld-example-app

**Comment by theodesp** [comment]
Epic

**Comment by theodesp** [comment]
I haven't received a reply from https://stackshare.io/. Maybe someone else can re-submit.

**Comment by rfschubert** [comment]
Just mailed again to StackShare Masonite.

**Comment by josephmancuso** [comment]
awesome :)

**Comment by kentaro0919** [comment]
I have done the http://www.todobackend.com/  https://mysterious-thicket-31854.herokuapp.com/

**Comment by vaibhavmule** [comment]
@theodesp Recently I tried submitting to stack share and found that name is already taken, Just wanted to know if you got an email from them or something?

**Comment by theodesp** [comment]
No. Maybe we can sent them an email about the status

**Comment by vaibhavmule** [comment]
Just an update, Masonite Realworld example has been merged into Realworld main repo.(https://github.com/gothinkster/realworld/pull/379)

https://github.com/vaibhavmule/masonite-realworld-example-app
