### ISSUE TITLE
Create a status map and allow integers to be returned as the status

### ISSUE THREAD

**Issue by josephmancuso** [MasoniteFramework/core#314]
right now the request status is very explicit:

```python
request.status('200 OK')
```

which is great because it is very explicit but if we want to return a permanent redirection we would need to do:

```python
request.status('301 Moved Permanently')
```

which means we can't typo or it will return a weird response. So we should be able to do something like:

```python
request.status(301)
```

What this will do is do some lookup in a dictionary key map that we put somewhere and return the correct response. Something like this:

```python
statuses = {
    301: '301 Moved Permanently' ,
    ...
}

def status(self, status):
    if ininstance(status, str):
        # no new logic, keep the logic as is.
    elsif instance(status, int):
        # lookup via the status map
        self.app().bind('StatusCode', statuses[status])
```

this is only the general concept. We can put the keymap in a `masonite/helper` file somewhere and then we can import it into the request class and maybe put it on the request class itself:

```python
from masonite.helpers.something import response_statuses
..
class Request:

    status = response_statuses()
```

maybe something like that?

**Comment by vaibhavmule** [comment]
I can work on this, for now we can just use status mentioned here https://developer.mozilla.org/en-US/docs/Web/HTTP/Status

**Comment by josephmancuso** [comment]
sounds good. ummm let's map all of them? Also should probably throw some exception if the `int` that they give is not a key in the mappings

**Comment by vaibhavmule** [comment]
Yup exception should be there, where do you think that this mapping file will be located?

**Comment by josephmancuso** [comment]
you might also have to test that the `request.get_status_code()` returns the full text based status code too

**Comment by josephmancuso** [comment]
that should actually work and theres a test for it already so we should be good

**Comment by josephmancuso** [comment]
just make sure doing something like:

```
request.status(500)

assert request.get_status_code() == '500 Internal Server Error'
```
