### ISSUE TITLE
Implement CORS Middleware

### ISSUE THREAD

**Issue by theodesp** [MasoniteFramework/core#320]
I'm trying to Create a Real World example backend using https://github.com/gothinkster/realworld and I noticed that the CORS middleware is missing. I recommend before we attempt to showcase the example to actually have one at hand.

See:
https://github.com/ottoyiu/django-cors-headers
https://github.com/corydolphin/flask-cors
https://github.com/barryvdh/laravel-cors

**Comment by hammacktony** [comment]
So essentially allow the ability to add more more items to the headers dictionary?

**Comment by josephmancuso** [comment]
but we don't have a built in middleware for that

**Comment by josephmancuso** [comment]
that `prefix_http=False` is actually annoying .. 🤔 maybe we should set it to false by default

**Comment by vaibhavmule** [comment]
@josephmancuso How can I add `request.header('CORS_ORIGIN_ALLOW_ALL', 'value here' prefix=False)` for every request?

**Comment by josephmancuso** [comment]
put it in a middleware before method

**Comment by josephmancuso** [comment]
and put the middleware inside the `HTTP_MIDDLEWARE` constant inside `config/middleware.py`

**Comment by hammacktony** [comment]
@josephmancuso In develop branch, it is `http_prefix=None`. Did something change?

**Comment by hammacktony** [comment]
So, something like this?

```
""" CORS Middleware """
from masonite.request import Request

class CORSMiddleware:

    def __init__(self, request: Request):
        self.request = request

    def after(self):
        if not self.request.header('Content-Type'):
            if isinstance(self.request.app().make('Response'), dict):
                cors = ""
                request.header('CORS_ORIGIN_ALLOW_ALL', cors, http_prefix=None)
            else:
                self.request.header(
                    'Content-Type', 'text/html; charset=utf-8', http_prefix=None)

```

**Comment by hammacktony** [comment]
I may have underestimated this project. Flask-Cors is a little more complicated.

**Comment by hammacktony** [comment]
```
""" CORS Middleware """
from masonite.request import Request

class CorsMiddleware:

    def __init__(self, request: Request):
        self.request = request

    def after(self):
        if not self.request.header('Content-Type'):
            if isinstance(self.request.app().make('Response'), dict):
                           
                '''
                |--------------------------------------------------------------------------
                | Create Dictionary of CORS headers
                |--------------------------------------------------------------------------
                |
                | Appends CORS headers to HTTP response
                |
                | Ex. cors = {"Access-Control-Allow-Origin": "*",
                |             "Access-Control-Allow-Headers": "Content-Type",
                |             "Access-Control-Allow-Methods": "DELETE, GET, HEAD, OPTIONS, PATCH, POST, PUT"}
                |
                '''

                cors = dict()
                
                for key in cors.keys():
                    self.request.header(key, cors[key], http_prefix=None)
```

**Comment by hammacktony** [comment]
How about that?

Not sure exactly how to test this either.

**Comment by josephmancuso** [comment]
cors needs to be a dictionary as a header? that seems weird to me 🤔

**Comment by josephmancuso** [comment]
although i'm not anywhere near an expert on cors so that could be right

**Comment by josephmancuso** [comment]
headers can't be dictionaries i'm pretty sure. I feel like this implementation would be:

```python
def before(self):
    self.request.header('Access-Control-Allow-Origin', 'value', http_prefix=None)
    self.request.header('Access-Control-Allow-Methods', 'value', http_prefix=None)
```

right? we are just setting CORS style headers as the response

**Comment by hammacktony** [comment]
I get what you are saying, I was thinking instead of writing out the `self.request.header('blah')` over and over again, just have it iterate through a dictionary.

I am not saying using `cors` directly. But, have that structure then iterate through it.
Look at the bottom of my code.
