### ISSUE TITLE
Implement JWT Middleware

### ISSUE THREAD

**Issue by theodesp** [MasoniteFramework/core#321]
I'm trying to Create a Real World example backend using https://github.com/gothinkster/realworld and I noticed that the JWT middleware is missing. I recommend before we attempt to showcase the example to actually have one at hand.

See:
http://getblimp.github.io/django-rest-framework-jwt/
https://github.com/jpadilla/pyjwt
https://github.com/tymondesigns/jwt-auth

**Comment by josephmancuso** [comment]
we technically do although it's not adapted to be middleware. This would be inside the `Entry` package

**Comment by hammacktony** [comment]
So, should we adapt this as middleware? Or leave it as is?

**Comment by josephmancuso** [comment]
This should reside in the Masonite entry package. It already exists but it needs to be adapted for middleware

**Comment by josephmancuso** [comment]
the entry package also needs a bit of a rewrite which i will have to get to

**Comment by josephmancuso** [comment]
pretty sure this is already in the new api package
