### ISSUE TITLE
craft controller blog should create BlogController class instead of blogController

### ISSUE THREAD

**Issue by vaibhavmule** [MasoniteFramework/core#331]
I was creating a controller using `craft` command. I ran `craft controller blog` and it created `blogController` I was expecting to be `BlogController`.

I feel it is no brainer that classes are always in Pascal Case and should keep in that way irrespective of what controller name user give.

**Comment by josephmancuso** [comment]
ummm i honestly think the first way is expected. If I type `blog` I feel like I should get `blogController` since `blog` is the kind of controller I want.

I see where this could be valid and i'll gladly reopen if more people want me to but I think we should keep it as is right now.

**Comment by vaibhavmule** [comment]
Sure, get your point.
