### ISSUE TITLE
Creating a controller should not have to type "Controller" at the end

### ISSUE THREAD

**Issue by josephmancuso** [MasoniteFramework/core#34]

**Comment by josephmancuso** [comment]
I'd like to keep this to be explicit. Not all controllers will need the name "Controller" in it but this is still likely to make it into 1.6

**Comment by mapeveri** [comment]
The change is in craft, no?. This issue should not be in craft repository?

**Comment by josephmancuso** [comment]
Well all commands are now in this repo for 1.6

**Comment by josephmancuso** [comment]
What I'm actually thinking of is that this should be solved but add a -e flag for exact

**Comment by mapeveri** [comment]
Ok, great! I simply add the word "Controller", do you think so?

**Comment by mapeveri** [comment]
For example?

**Comment by josephmancuso** [comment]
So we can do craft controller Test which makes a TestController controller or we can do craft controller Test -e which will make a Test controller

**Comment by josephmancuso** [comment]
The -e flag will simply just not append controller to the end of the controller

**Comment by mapeveri** [comment]
For example:

craft controller Dashboard

It will create "DashboardController"

craft controller Dashboard -e

It will create "Dashboard"

It's ok?
