### ISSUE TITLE
add request.pop method to docs

### ISSUE THREAD

**Issue by josephmancuso** [MasoniteFramework/core#341]

**Comment by clsource** [comment]
For helping the documentation process

here is the function definition
https://github.com/MasoniteFramework/core/blob/633c19773134d421785c6476da6591aefa85f76f/masonite/request.py#L781

and here are the tests
https://github.com/MasoniteFramework/core/blob/633c19773134d421785c6476da6591aefa85f76f/tests/test_requests.py#L400

**Comment by nioperas06** [comment]
Is this method (`pop`) useful? 🤔

**Comment by josephmancuso** [comment]
if you want to remove variables from the request, maybe for validating you want to pop the csrf token

**Comment by josephmancuso** [comment]
i think this is completed. Can reopen if its not
