### ISSUE TITLE
Send Verify Email on User Registration

### ISSUE THREAD

**Issue by mitchdennett** [MasoniteFramework/core#342]
Have a way to send a Verify Email automatically when a user is registered.
Base it off an HTML template. 

Also have a middleware to redirect a user if they haven't verified email yet.

Let me know what you think and if this is a good idea to include into Core. 
I wouldn't mind implementing this one.

**Comment by josephmancuso** [comment]
👍

**Comment by josephmancuso** [comment]
fixed
