### ISSUE TITLE
Can we have expected release date on Major, Minor PR?

### ISSUE THREAD

**Issue by vaibhavmule** [MasoniteFramework/core#343]
https://github.com/MasoniteFramework/core/pull/325
https://github.com/MasoniteFramework/core/pull/230

I was just looking for when this gonna release, or is there any documentation for Masonite release cycle?

**Comment by clsource** [comment]
Here are some guidelines https://docs.masoniteproject.com/prologue/release-cycle

Maybe a Calver https://calver.org/
would benefit the development releases though.

I think a dev release every 28 days would be acceptable.

**Comment by vaibhavmule** [comment]
Thanks for the link and also I would suggest to include expected release date in description of PR.

**Comment by josephmancuso** [comment]
done

**Comment by josephmancuso** [comment]
@clsource minor release every 2 weeks. Major release every 6 months. Beta released every 1 month starting 4 months out.

**Comment by vaibhavmule** [comment]
That's a best summary of release cycle, that like TLDR of release cycle for Masonite.
