### ISSUE TITLE
Create Masonite Packages Site

### ISSUE THREAD

**Issue by theodesp** [MasoniteFramework/core#347]
For example:
https://djangopackages.org/
http://cookiecutter-templates.sebastianruml.name/

**Comment by vaibhavmule** [comment]
I was actually thinking of creating one.

Currently, there are few packages for Masonite, that is why I dropped that idea and created [Awesome Masonite](https://github.com/vaibhavmule/awesome-masonite) and included official packages.

But it is good ideas, as a developer can have the ability to search the packages related to masonite.

**Comment by clsource** [comment]
@vaibhavmule seems cool.
maybe awesome masonite could have a json (or hjson) file in the repo and a github page
so people could search using a simple form 👍

**Comment by vaibhavmule** [comment]
@clsource I'm open to PR and but if you are asking about the gh-pages, it is available at. https://vaibhavmule.com/awesome-masonite/

**Comment by josephmancuso** [comment]
This was basically made in the site above: https://awesome.masoniteproject.com/finder/
