### ISSUE TITLE
run flake8 on travis ci

### ISSUE THREAD

**Issue by vaibhavmule** [MasoniteFramework/core#355]
- add Command to `.travis.yml`: `flake8 masonite/ --ignore=E501,F401,E128,E402,E731,F821,E712`
- add `flake8` to `requirements.txt`
- add `flake8` [configuration](http://flake8.pycqa.org/en/latest/user/configuration.html) to `setup.cfg`

**Comment by w3x10e8** [comment]
Hey can i fix this?

**Comment by josephmancuso** [comment]
go for it

**Comment by josephmancuso** [comment]
base off of master branch
