### ISSUE TITLE
Create a way to generate a table definition as a docstring

### ISSUE THREAD

**Issue by josephmancuso** [MasoniteFramework/core#359]
# NOTE: This issue should branch off of master and go into the next minor release (if the change will be backwards compatible with 2.0.x)

I personally always use some kind of dbms client like MySQL workbench but a lot of others do not. This is an issue because Active Record style ORM's "take the shape" of the table when they fetch the schema. This makes the developer have to keep the schema in his head when accessing models.

@mitchdennett and I have agreed upon a good solution with is to generate the schema into a docstring from a command.

The command should look like:

```
$ craft model:docstring --table users
```

which should generate the schema, lengths and defaults for the table as a docstring and output it to the terminal:

```
$ craft model:definition --table users

""" User definition (generated with love by Masonite)
    
first_name: varchar(255) default: None
email: varchar(75) default: None
active: int() default: 1
"""
```

see here for more background of the conversation https://github.com/MasoniteFramework/craft/issues/15

**Comment by hammacktony** [comment]
This is pretty cool. What is the status on this?

**Comment by josephmancuso** [comment]
Pretty sure nobody has taken it yet

**Comment by josephmancuso** [comment]
i'm gonna take this tonight and see what I come up with

**Comment by hammacktony** [comment]
I looked into the Orator github....nothing really. There is a method tucked away that should provide some help, but no documentation. SMH

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by hammacktony** [comment]
Look at [this](https://github.com/sdispater/orator/blob/0.9/orator/dbal/schema_manager.py). 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by hammacktony** [comment]
Look at the `list_table_details` method. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by josephmancuso** [comment]
might be useful. I think I implemented something similiar to this for the dashboard. I'll try to see if I can scrummage up some old code

**Comment by josephmancuso** [comment]
https://github.com/MasoniteFramework/core/pull/420
