### ISSUE TITLE
Create Resource Routes

### ISSUE THREAD

**Issue by josephmancuso** [MasoniteFramework/core#36]
Masonite 1.5 will focus on bug fixes and API's. This issue will be one of the leading issues to complete.

Require #41 to be closed

A Resource route will be called something like: `UserResource` where it's whole purpose is to be a class that returns Json or something.

Now this `UserResource` will need to run a `serialize` method which will be inherited by a base class which will come from `JsonSerialize` or `XmlSerialize` or something.

Masonite will need to now accept `GET`, `POST`, `PUT`, `PATCH`, `DELETE`.

This is simple as all the logic is there but it only currently is set to run on `POST` requests.

I'm thinking the user resource might look something like:

```python

from app.User import User

class UserResource:

## basic methods

    def to_array(self):
        return {
            'id': self.id,
            'username': self.username
        }


## Special Methods:

    def with():
        pass
```

Then inside the `routes/api.py` should look something like:

```python
from masonite.resources import Resource

from app.http.resources.UserResource import UserResource
from app.User import User
ROUTES = [
    Resource(UserResource(User))
]
```

or 

```python
ROUTES = [
    UserResource(User),
    DashboardResource(Dashboard),
    ListResource(List),
]
```

And that should automatically handle show, store, update, destroy

**Comment by josephmancuso** [comment]
Ok so the work that is done so far. I will comment what I have so far to do a sort of documentation driven design.

****

First you will create a resource. Resources will basically be api endpoints. to do this, you will run:

    $ craft resource UserResource

This will create a resource in `app/http/resources/UserResource.py` that will look like this:

```python
from masonite.api.Resource import Resource
from masonite.api.JsonSerialize import JsonSerialize

class UserResource(Resource, JsonSerialize):
    model = None
```

Then just add your model to it:

```python
from masonite.api.Resource import Resource
from masonite.api.JsonSerialize import JsonSerialize
from app.User import User

class UserResource(Resource, JsonSerialize):
    model = User
```

You will then add this to your `RESOURCES` list inside the `routes/api.py` file along with the model you want to attach to it like so:

```python
from app.http.resources.UserResource import UserResource
RESOURCES = [
    UserResource()
]
```

bam. Done.

Now you will have access to:

`GET /api/users` <-- read all
`GET /api/user/1` <-- read 1
`POST /api/users` <-- create
`PUT /api/user/1` <-- update
`DELETE /api/users` <-- delete

Now this API is now open to anyone right? Anyone can create input into our API. We might not want that. So let's add a token authentication. We can do so by simply inheriting from a class.


```python
from masonite.api.Resource import Resource
from masonite.api.JsonSerialize import JsonSerialize
from masonite.api.TokenAuthentication import TokenAuthentication
from app.User import User

class UserResource(Resource, JsonSerialize, TokenAuthentication):
    model = User
    
    # the model that has a `token` column
    # could be it's own Token class and probably will be once this is done
    authentication_model = User 
```

We now have complete token authentication. It will intercept the request and authenticate first before continuing. If the request is not authenticated with a correct token then it will return something like:

```json
{ 
    "Error": "Invalid authentication token"
}
```

but if the correct token is sent then it will give access to the API

@mapeveri What do you think? is this simple and intuitive enough?

**Comment by mapeveri** [comment]
@josephmancuso it's awesome! One thing, should be the possibility of override in the methods in resource class.

**Comment by josephmancuso** [comment]
yeah well you can just because it's python so you can overwrite the authentication just by doing:

```python
class UserResource(Resource, JsonSerialize, TokenAuthentication):
    model = User

    exclude = ['id', 'email']
    
    # the model that has a `token` column
    # could be it's own Token class and probably will be once this is done
    authentication_model = User 

    def authenticate(self):
        # all authentication stuff here
```

**Comment by mapeveri** [comment]
Exactly, but what I mean are the methods of the http verbs.

**Comment by mapeveri** [comment]
No, I mean this. For example, if I want to override the delete method:

```
class UserResource(Resource, JsonSerialize, TokenAuthentication):
    model = User

    exclude = ['id', 'email']
    
    # the model that has a `token` column
    # could be it's own Token class and probably will be once this is done
    authentication_model = User 

    def delete(self):
        # Override ...
```

Also for example, in the resource, I just want to have the GET and POST methods, I should be able to do so:

```
class UserResource(Resource, JsonSerialize, TokenAuthentication):
    model = User
    methods = ['GET', 'POST']
    exclude = ['id', 'email']
```

**Comment by josephmancuso** [comment]
Oh I see where you're going. I like that I'll implement something like this

**Comment by mapeveri** [comment]
Great!

**Comment by josephmancuso** [comment]
Ok so I want to keep the `create`, `read`, `update`, `delete` methods in mind because that makes building API's simple so I implemented it like this:

```python
class UserResource(Resource, JsonSerialize, TokenAuthentication):
    model = User
    methods = ['read', 'create']
    exclude = ['id', 'email']
```

Now this endpoint can only be read and created but not updated or deleted.

**Comment by josephmancuso** [comment]
I'm actually thinking of making this it's own package .. but installing it by default (minus all the actual integration stuff)

**Comment by mapeveri** [comment]
I would leave the name of the http verbs. I think is more "standar".

**Comment by josephmancuso** [comment]
yeah but the verbs can change. for example you might want to change a DELETE to a POST so the http verbs are going to be fluid but the create, read, update, delete are going to be concrete.

In other words when building out a delete form, forms can only do GET and POST so you might want to just make it POST. the http verbs are going to be fluid. I'm just trying to think ahead on what the user might want to change on a per resource basis. Not easy to predict the future

**Comment by josephmancuso** [comment]
https://github.com/MasoniteFramework/entry is also where this feature will live. It's such a large feature that it should really live in it's own repository. It was making this repository too bloated and hard to maintain.
