### ISSUE TITLE
Tests cases for the commands in `core` and `craft` repositories

### ISSUE THREAD

**Issue by vaibhavmule** [MasoniteFramework/core#363]
_Originally posted by @vaibhavmule in https://github.com/MasoniteFramework/core/pull/362/comment#issuecomment-423822732_

**Comment by josephmancuso** [comment]
not sure if we can test these. Most of these commands are small but scaffold classes. I think @clsource was working on a way to do this. I'll close for now to get this out of the way but if @clsource wants to chime in. I remember seeing some issues and PR a while back about testing file commands but not sure where it went.
