### ISSUE TITLE
Add Log Mail Driver for test purposes.

### ISSUE THREAD

**Issue by mitchdennett** [MasoniteFramework/core#371]
It could be nice to have another mail driver that just prints out the email string/html to a log or console especially when developing/test.

**Comment by vaibhavmule** [comment]
I agree with as it will help a lot i development

**Comment by josephmancuso** [comment]
oh that'd be really cool

**Comment by mitchdennett** [comment]
I'll take this if no one else has started

**Comment by mitchdennett** [comment]
Yeah just the terminal for now.  We could probably have an option in Mail.py to enter a file and then save the log to a file instead.

See below:

![screen shot 2018-09-30 at 9 26 45 pm](https://user-images.githubusercontent.com/16268619/46265762-b5bf9d00-c4f7-11e8-9fc4-21338bd264cf.png)

**Comment by josephmancuso** [comment]
this is being worked on in the PR listed above ☝️
