### ISSUE TITLE
Upgrading packages used by Masonite Core

### ISSUE THREAD

**Issue by vaibhavmule** [MasoniteFramework/core#372]
Making sure most of the package are up to date with the latest version.

Please base of from `develop` branch.

**Comment by vaibhavmule** [comment]
This might be added for https://github.com/MasoniteFramework/core/labels/beta-3

**Comment by josephmancuso** [comment]
sounds good. I think a lot of them are already up to date but also keep in mind that we are also limited to the versions of Orator. I believe Orator needs pendulum 1.5 so that cannot be updated

**Comment by josephmancuso** [comment]
pretty sure I have made these up to date
