### ISSUE TITLE
Dark Mode for Exception

### ISSUE THREAD

**Issue by vaibhavmule** [MasoniteFramework/core#373]
Giving an ability to the developer to chose the dark mode for Exception page.

![screenshot 2018-09-28 at 7 09 15 pm](https://user-images.githubusercontent.com/6290791/46212272-31341980-c353-11e8-85e7-4a1c11743e89.png)

This is an example screenshot generated using https://darkreader.org/

![screenshot 2018-09-28 at 7 14 08 pm](https://user-images.githubusercontent.com/6290791/46212390-7ce6c300-c353-11e8-99f5-ede1693eb50f.png)

**Comment by josephmancuso** [comment]
how would you choose between them?

**Comment by vaibhavmule** [comment]
We can add a toggle to Exception page, also need to think about work around in the framework.

**Comment by josephmancuso** [comment]
ehh i think this is cool but not sure if it's any more useful than a light version.
