### ISSUE TITLE
Bootstrap 4 Supports for Masonite Dashboard Template

### ISSUE THREAD

**Issue by vaibhavmule** [MasoniteFramework/core#377]
Here are template based on Bootstrap 3, I'm suggesting to support Bootstrap 4 as it is the latest version of Bootstrap.

You can find dashboard templates here: 
https://github.com/MasoniteFramework/dashboard/tree/master/dashboard/templates/dashboard

**Comment by josephmancuso** [comment]
agreed. 👍

**Comment by vaibhavmule** [comment]
Nobody is working on it, you can take it.

**Comment by hammacktony** [comment]
What is the progress on this issue?

**Comment by rickwest** [comment]
@hammacktony @josephmancuso Should be done with this today :-)

**Comment by josephmancuso** [comment]
I think this was completed
