### ISSUE TITLE
Code Of Conduct to be moved from CONTRIBUTING.md to CODE_OF_CONDUCT.md

### ISSUE THREAD

**Issue by vaibhavmule** [MasoniteFramework/core#380]
- create new file CODE_OF_CONDUCT.md
- move [Code Of Conduct section](https://github.com/MasoniteFramework/core/blob/2.0/CONTRIBUTING.md#code-of-conduct) from [CONTRIBUTING.md](https://github.com/MasoniteFramework/core/blob/develop/CONTRIBUTING.md) to CODE_OF_CONDUCT.md

**Comment by josephmancuso** [comment]
sure 👍

**Comment by josephmancuso** [comment]
fixed
