### ISSUE TITLE
use of `providers` folder of Masonite App.

### ISSUE THREAD

**Issue by vaibhavmule** [MasoniteFramework/core#393]
Does this folder require? If yes, why?

https://github.com/MasoniteFramework/masonite/tree/develop/app/providers

**Comment by vaibhavmule** [comment]
ah, I get it.

**Comment by josephmancuso** [comment]
yeah. Also 2.0 had providers but the features that 2.1 have sort of made the providers obsolete so i've removed them for 2.1
