### ISSUE TITLE
inherit BaseScaffoldCommand for Controller Command

### ISSUE THREAD

**Issue by vaibhavmule** [MasoniteFramework/core#397]
**Controller Commnad:** https://github.com/MasoniteFramework/core/blob/develop/masonite/commands/ControllerCommand.py

The Controller command should use `BaseScaffoldCommand` to generate the Controller file. 

If required, make appropriate changes in BaseScaffoldCommand while making sure Model, Middleware, Job command works as expected. 

**Usage of BaseScaffoldCommand**
Model: https://github.com/MasoniteFramework/core/blob/develop/masonite/commands/ModelCommand.py
Middleware: https://github.com/MasoniteFramework/core/blob/develop/masonite/commands/MiddlewareCommand.py
Job: https://github.com/MasoniteFramework/core/blob/develop/masonite/commands/JobCommand.py

**Comment by josephmancuso** [comment]
yeah the trick is that we have an option on that command class so we somehow need to support 2 different templates using the base scaffold command

**Comment by vaibhavmule** [comment]
Yes, that is the trick. I'm not sure how it is going to work as controller command has 2 options.

```python
        {--r|--resource : Create a controller as a resource}
        {--e|--exact : For add the name controller without `Controller` text}
```

**Comment by josephmancuso** [comment]
yeah I say for now we just leave this as is
