### ISSUE TITLE
change the line `NAME = 'Masonite 2.1'` in config/application.py

### ISSUE THREAD

**Issue by vaibhavmule** [MasoniteFramework/core#399]
change the line `NAME = 'Masonite 2.1'` with `NAME = os.getenv('APP_NAME', 'Masonite 2.1')`

Link to Line: https://github.com/MasoniteFramework/masonite/blob/master/config/application.py#L16

Base of from `master` branch

**Comment by RonitRay** [comment]
Hi, can I work on this?
