### ISSUE TITLE
Improve Upload drivers

### ISSUE THREAD

**Issue by bjorntheart** [MasoniteFramework/core#400]
## Better Exception handling

New upload driver implementations in `class Upload*Driver` should handle exceptions raised from third party libraries. At the very least catch exceptions and log the error message to an `error.log` or `sys.stdout`. We'll leave it up to the driver calling code — typically a Controller, but it could also be a job queue worker — to gracefully handle upload errors

## Resolve driver config with multiple words to PascalCase class names

Add support for resolving PascalCase class names from a storage driver configuration containing multiple words such as `digitalocean`. I ran into a slight annoyance while working on the DigitalOcean driver implementation. The storage configuration is resolved from the value of `DRIVER` in `config/storage.py` which in this case is `digitalocean`. The class name resolves to `UploadDigitaloceanDriver` instead of following a better PascalCase naming convention of `UploadDigitalOceanDriver`. This happens because of the following code in `masonite/managers/Manager.py`:
```python
def create_driver(self, driver=None):
    if not driver:
        driver = self.container.make(self.config).DRIVER.capitalize()
    else:
        if isinstance(driver, str):
            driver = driver.capitalize()

    try:
        if isinstance(driver, str):
            self.manage_driver = self.container.make(
                '{0}{1}Driver'.format(self.driver_prefix, driver)
            )
            return
        elif inspect.isclass(driver):
            self.manage_driver = driver
            return

        raise UnacceptableDriverType(
            'String or class based driver required. {} driver recieved.'.format(driver))
    except MissingContainerBindingNotFound:
        raise DriverNotFound(
            'Could not find the {0}{1}Driver from the service container. Are you missing a service provider?'.format(self.driver_prefix, driver))
```
With that being said I don't think this is a bug, but it might just come down to my own personal preference. I like to name classes containing multiple words by capitalizing each word for better visual presentation.

At this moment I also haven't thought of a good solution to make this work :-)

## Provide more options for naming uploaded files

When I think filenames in the context of uploading files, I see users wanting these options

1. upload the file with the original filename -`testme.png`
2. upload the file with a totally random string generated filename - `3bcc367a3488e113dca68b67e5fa262fe4fd2df48b1b72fd3292b30358911aab.png` in this case I **sha256** the filename
3. combination of 1 and 2 - `testme-3bcc367a3488e113dca68b67e5fa262fe4fd2df48b1b72fd3292b30358911aab.png`

**Comment by josephmancuso** [comment]
@bjorntheart any thoughts on number 2 yet?

**Comment by bjorntheart** [comment]
I quick and dirty solutions is to just **md5** the filename without the extension and append the extension again afterwards, but perhaps we should leave it up to the user to decide what naming convention they want to use. I actually don't think this is something we should care about adding to core. What I do think we should add is a extra parameter to the  `store()` method of the upload driver to which you can pass a _filename_. 

See the following example

```python
def store(self, fileitem, filename=None, location=None):
    
    _filename = filename if filename else os.path.basename(fileitem.filename)

    # Check if is a valid extension
    self.validate_extension(_filename)    

    location = self.get_location(location)
    if not location.endswith('/'):
        location += '/'

    open(location + _filename, 'wb').write(fileitem.file.read())

    self.file_location = location + _filename

    return _filename
```

**Comment by bjorntheart** [comment]
@josephmancuso thoughts?

**Comment by josephmancuso** [comment]
yeah sure i'm not against it. Seems easy enough

**Comment by bjorntheart** [comment]
I’ll take this one. Do I branch off of 2.1?

**Comment by vaibhavmule** [comment]
Based off from `develop` branch

**Comment by josephmancuso** [comment]
any breaking changes on this need to be done before next weekend, November 24th. This will give enough time to test and get docs updated if need be

**Comment by josephmancuso** [comment]
this is one completed
