### ISSUE TITLE
Resourceful route to a controller

### ISSUE THREAD

**Issue by nioperas06** [MasoniteFramework/core#404]
```
from masonite.helpers.routes import resource

...
resource('tasks', 'TaskController'), 
...
```
🤔 
[Laravel Resource Controller](https://laravel.com/docs/5.7/controllers#resource-controllers)

**Comment by nioperas06** [comment]
Writing some basic CRUD blog post and I think this would be awesome 👍

**Comment by josephmancuso** [comment]
yup this is actually very possible with the new `Match` route. 

here is a perfect example of how that would be done https://github.com/MasoniteFramework/api/blob/master/api/resources/Resource.py#L27-L40

**Comment by vaibhavmule** [comment]
Adding here for notes.

The `Resources` route is just a collection of CRUD routes, whether is it API or rendering templates.

Resources will have following routes:
```
GET     /users           UserController@index
GET     /users/:id/edit  UserController@edit
GET     /users/new       UserController@new
GET     /users/:id       UserController@show
POST    /users           UserController@create
PATCH   /users/:id       UserController@update
PUT     /users/:id       UserController@update
DELETE  /users/:id       UserController@delete 
```

```python
from masonite.routes import Resources

ROUTES = [
    Resources().route('/users', 'UserController'),
    Resources().route('/users', 'PostController').only('index', 'show'),
    Resources().route('/users', 'CommentController').without('delete'),
]
 
```

Inspiration from Phoenix, https://hexdocs.pm/phoenix/routing.html#resources

**Comment by josephmancuso** [comment]
This should prob be done like so:

```python
from masonite.routes import Route

ROUTES = [
    Route().resource('/user', without=['delete', 'update'])
]
```

which will produce something like above:

```python
GET     /users           UserController@index
GET     /users/:id/edit  UserController@edit
GET     /users/new       UserController@new
GET     /users/:id       UserController@show
POST    /users           UserController@create
PUT / PATCH   /users/:id       UserController@update
DELETE  /users/:id       UserController@delete 
```

but we will have to work on the resource methods. I'm not a huge fan of `create` and `new`. Whatever methods we go with should be extremely obvious what they are suppose to contain. Honestly even look at `index`, is that suppose to be 1 or all of the records?

**Comment by vaibhavmule** [comment]
Regarding, the naming convention for this, we have to give a thought before this gets implemented.

What I have mentioned here is what other framework trying to solve this problem. 

Definitely, We should come up with better naming for each route.

**Comment by josephmancuso** [comment]
closing but will reopen if new ideas come through

**Comment by vaibhavmule** [comment]
@josephmancuso Can we reopen this? I feel when things are CRUD, `resource` helps in having 1 line declaration as compared to 7 lines.

**Comment by vaibhavmule** [comment]
This in 2.2?

**Comment by nioperas06** [comment]
@vaibhavmule  No.

**Comment by rodrigoSyscop** [comment]
How about:
```python
from masonite.routes import Route

ROUTES = [
    Route().resource('/user', 'UserController')
]
```

HTTP Verb | Route | Controller@method
-|-|-
GET | /users | UserController@index
GET | /users/create | UserController@create
POST | /users | UserController@store
GET | /users/@id | UserController@show
GET | /users/@id/edit | UserController@edit
PUT / PATCH |  /users/@id | UserController@update
DELETE | /users/@id | UserController@destroy

**Comment by sphinxxanxus** [comment]
@nioperas06 @josephmancuso 
We can add `**kwargs` parameter to take directly `names` of routes, `middleware` too. 
Like this:

> ```python
> from masonite.routes import Route
> 
> ROUTES = [
>   Route().resource('user', 'UserController',
>                               names={'create': 'user.create', 'index': 'user.all'},
>                               middleware=['auth', 'jwt'])
> ]

**PS:** I am already working on issue. And I also add `api_resource` function

> How about:
> 
> ```python
> from masonite.routes import Route
> 
> ROUTES = [
>     Route().resource('/user', 'UserController')
> ]
> ```
> 
> HTTP Verb	Route	Controller@method
> GET	/users	UserController@index
> GET	/users/create	UserController@create
> POST	/users	UserController@store
> GET	/users/@id	UserController@show
> GET	/users/@id/edit	UserController@edit
> PUT / PATCH	/users/@id	UserController@update
> DELETE	/users/@id	UserController@destroy

**Comment by Marlysson** [comment]
```
GET /users/create UserController@create
GET /users/@id/edit UserController@edit
```
A GET to a edit/create action on resource? Instead don't would be PATCH or PUT method..?

**Comment by schererja** [comment]
@Marlysson I think the edit/create actions are to get a template, not to actually create a resource or to edit a resource.  This was one of those things that originally took me a bit to get my head wrapped around.  I'd agree with @rodrigoSyscop, that looks about the cleanest that can be done.
