### ISSUE TITLE
List of missing docstrings throughout the code

### ISSUE THREAD

**Issue by vaibhavmule** [MasoniteFramework/core#432]
masonite/exceptions.py:1 in public class `DriverNotFound`:
        D101: Missing docstring in public class
masonite/exceptions.py:5 in public class `DriverLibraryNotFound`:
        D101: Missing docstring in public class
masonite/exceptions.py:9 in public class `FileTypeException`:
        D101: Missing docstring in public class
masonite/exceptions.py:13 in public class `RequiredContainerBindingNotFound`:
        D101: Missing docstring in public class
masonite/exceptions.py:17 in public class `MissingContainerBindingNotFound`:
        D101: Missing docstring in public class
masonite/exceptions.py:21 in public class `UnacceptableDriverType`:
        D101: Missing docstring in public class
masonite/exceptions.py:25 in public class `ContainerError`:
        D101: Missing docstring in public class
masonite/exceptions.py:29 in public class `InvalidCSRFToken`:
        D101: Missing docstring in public class
masonite/exceptions.py:33 in public class `InvalidHTTPStatusCode`:
        D101: Missing docstring in public class
masonite/exceptions.py:37 in public class `RouteMiddlewareNotFound`:
        D101: Missing docstring in public class
masonite/exceptions.py:41 in public class `ResponseError`:
        D101: Missing docstring in public class
masonite/exceptions.py:45 in public class `InvalidAutoloadPath`:
        D101: Missing docstring in public class
masonite/exceptions.py:49 in public class `AutoloadContainerOverwrite`:
        D101: Missing docstring in public class
masonite/exceptions.py:53 in public class `InvalidSecretKey`:
        D101: Missing docstring in public class
masonite/exceptions.py:57 in public class `StrictContainerException`:
        D101: Missing docstring in public class
masonite/exceptions.py:61 in public class `InvalidRouteCompileException`:
        D101: Missing docstring in public class
masonite/exceptions.py:65 in public class `RouteException`:
        D101: Missing docstring in public class
masonite/routes.py:412 in public class `ViewRoute`:
        D101: Missing docstring in public class
masonite/middleware/MaintenanceModeMiddleware.py:7 in public class `MaintenanceModeMiddleware`:
        D101: Missing docstring in public class
masonite/middleware/JsonResponseMiddleware.py:5 in public class `JsonResponseMiddleware`:
        D101: Missing docstring in public class
masonite/contracts/CacheContract.py:4 in public class `CacheContract`:
        D101: Missing docstring in public class
masonite/contracts/UploadContract.py:4 in public class `UploadContract`:
        D101: Missing docstring in public class
masonite/contracts/SessionContract.py:4 in public class `SessionContract`:
        D101: Missing docstring in public class
masonite/contracts/BroadcastContract.py:4 in public class `BroadcastContract`:
        D101: Missing docstring in public class
masonite/contracts/MailContract.py:4 in public class `MailContract`:
        D101: Missing docstring in public class
masonite/contracts/QueueContract.py:4 in public class `QueueContract`:
        D101: Missing docstring in public class
masonite/contracts/managers/SessionManagerContract.py:4 in public class `SessionManagerContract`:
        D101: Missing docstring in public class
masonite/contracts/managers/BroadcastManagerContract.py:4 in public class `BroadcastManagerContract`:
        D101: Missing docstring in public class
masonite/contracts/managers/CacheManagerContract.py:4 in public class `CacheManagerContract`:
        D101: Missing docstring in public class
masonite/contracts/managers/MailManagerContract.py:4 in public class `MailManagerContract`:
        D101: Missing docstring in public class
masonite/contracts/managers/UploadManagerContract.py:4 in public class `UploadManagerContract`:
        D101: Missing docstring in public class
masonite/contracts/managers/QueueManagerContract.py:4 in public class `QueueManagerContract`:
        D101: Missing docstring in public class
masonite/testsuite/TestRequest.py:5 in public class `TestRequest`:
        D101: Missing docstring in public class
masonite/testsuite/TestRoute.py:5 in public class `TestRoute`:
        D101: Missing docstring in public class
masonite/testsuite/TestSuite.py:39 in public class `TestSuite`:
        D101: Missing docstring in public class
masonite/providers/QueueProvider.py:10 in public class `QueueProvider`:
        D101: Missing docstring in public class
masonite/providers/WhitenoiseProvider.py:8 in public class `WhitenoiseProvider`:
        D101: Missing docstring in public class
masonite/providers/AppProvider.py:24 in public class `AppProvider`:
        D101: Missing docstring in public class
masonite/providers/CsrfProvider.py:7 in public class `CsrfProvider`:
        D101: Missing docstring in public class
masonite/providers/ViewProvider.py:7 in public class `ViewProvider`:
        D101: Missing docstring in public class
masonite/providers/HelpersProvider.py:13 in public class `HelpersProvider`:
        D101: Missing docstring in public class
masonite/providers/SassProvider.py:7 in public class `SassProvider`:
        D101: Missing docstring in public class
masonite/providers/MailProvider.py:10 in public class `MailProvider`:
        D101: Missing docstring in public class
masonite/providers/SessionProvider.py:12 in public class `SessionProvider`:
        D101: Missing docstring in public class
masonite/providers/BroadcastProvider.py:10 in public class `BroadcastProvider`:
        D101: Missing docstring in public class
masonite/providers/StatusCodeProvider.py:6 in public class `ServerErrorExceptionHook`:
        D101: Missing docstring in public class
masonite/providers/StatusCodeProvider.py:26 in public class `StatusCodeProvider`:
        D101: Missing docstring in public class
masonite/providers/RouteProvider.py:9 in public class `RouteProvider`:
        D101: Missing docstring in public class
masonite/providers/StartResponseProvider.py:8 in public class `StartResponseProvider`:
        D101: Missing docstring in public class
masonite/providers/UploadProvider.py:12 in public class `UploadProvider`:
        D101: Missing docstring in public class
masonite/providers/CacheProvider.py:10 in public class `CacheProvider`:
        D101: Missing docstring in public class
masonite/testing/UnitTest.py:8 in public class `UnitTest`:
        D101: Missing docstring in public class
masonite/testing/MockJson.py:5 in public class `MockJson`:
        D101: Missing docstring in public class
masonite/testing/MockRoute.py:8 in public class `MockRoute`:
        D101: Missing docstring in public class
masonite/testing/BaseRequest.py:1 in public class `BaseRequest`:
        D101: Missing docstring in public class
masonite/testing/MockRequest.py:5 in public class `MockRequest`:
        D101: Missing docstring in public class
masonite/testing/MockController.py:1 in public class `MockController`:
        D101: Missing docstring in public class
masonite/commands/ServeCommand.py:196 in public class `ReloaderLoop`:
        D101: Missing docstring in public class
masonite/commands/ServeCommand.py:239 in public class `WatchdogReloaderLoop`:
        D101: Missing docstring in public class

masonite/__init__.py:1 at module level:
        D104: Missing docstring in public package
masonite/packages.py:7 in public function `create_or_append_config`:
        D103: Missing docstring in public function
masonite/packages.py:34 in public function `append_web_routes`:
        D103: Missing docstring in public function
masonite/packages.py:50 in public function `append_api_routes`:
        D103: Missing docstring in public function
masonite/packages.py:66 in public function `create_controller`:
        D103: Missing docstring in public function
masonite/packages.py:88 in public function `add_venv_site_packages`:
        D103: Missing docstring in public function
masonite/view.py:212 in public method `test`:
        D102: Missing docstring in public method
masonite/view.py:295 in public method `set_splice`:
        D102: Missing docstring in public method
masonite/app.py:272 in public method `swap`:
        D102: Missing docstring in public method
masonite/exceptions.py:1 at module level:
        D100: Missing docstring in public module
masonite/routes.py:113 in public method `compile`:
        D102: Missing docstring in public method
masonite/routes.py:152 in public method `view`:
        D102: Missing docstring in public method
masonite/routes.py:204 in public method `get_response`:
        D102: Missing docstring in public method
masonite/routes.py:432 in public method `get_response`:
        D102: Missing docstring in public method
masonite/snippets/__init__.py:1 at module level:
        D104: Missing docstring in public package
masonite/snippets/auth/controllers/ConfirmController.py:75 in public method `send_verify_email`:
        D102: Missing docstring in public method
masonite/snippets/auth/controllers/HomeController.py:11 in public method `__init__`:
        D102: Missing docstring in public method
masonite/snippets/auth/controllers/HomeController.py:14 in public method `show`:
        D102: Missing docstring in public method
masonite/middleware/MaintenanceModeMiddleware.py:9 in public method `__init__`:
        D102: Missing docstring in public method
masonite/middleware/MaintenanceModeMiddleware.py:12 in public method `before`:
        D102: Missing docstring in public method
masonite/middleware/__init__.py:1 at module level:
        D104: Missing docstring in public package
masonite/middleware/JsonResponseMiddleware.py:1 at module level:
        D100: Missing docstring in public module
masonite/middleware/JsonResponseMiddleware.py:7 in public method `__init__`:
        D102: Missing docstring in public method
masonite/middleware/JsonResponseMiddleware.py:10 in public method `after`:
        D102: Missing docstring in public method
masonite/middleware/CsrfMiddleware.py:14 in public method `__init__`:
        D102: Missing docstring in public method
masonite/middleware/CsrfMiddleware.py:19 in public method `before`:
        D102: Missing docstring in public method
masonite/middleware/CsrfMiddleware.py:27 in public method `after`:
        D102: Missing docstring in public method
masonite/drivers/BroadcastAblyDriver.py:33 in public method `channel`:
        D402: First line should not be the function's "signature"
masonite/drivers/__init__.py:1 at module level:
        D104: Missing docstring in public package
masonite/drivers/BroadcastPusherDriver.py:33 in public method `channel`:
        D402: First line should not be the function's "signature"
masonite/auth/MustVerifyEmail.py:11 in public method `verify_email`:
        D102: Missing docstring in public method
masonite/auth/__init__.py:1 at module level:
        D104: Missing docstring in public package
masonite/contracts/CacheContract.py:1 at module level:
        D100: Missing docstring in public module
masonite/contracts/CacheContract.py:7 in public method `store`:
        D102: Missing docstring in public method
masonite/contracts/CacheContract.py:11 in public method `store_for`:
        D102: Missing docstring in public method
masonite/contracts/CacheContract.py:15 in public method `get`:
        D102: Missing docstring in public method
masonite/contracts/CacheContract.py:19 in public method `is_valid`:
        D102: Missing docstring in public method
masonite/contracts/CacheContract.py:23 in public method `exists`:
        D102: Missing docstring in public method
masonite/contracts/UploadContract.py:1 at module level:
        D100: Missing docstring in public module
masonite/contracts/UploadContract.py:7 in public method `accept`:
        D102: Missing docstring in public method
masonite/contracts/UploadContract.py:11 in public method `validate_extension`:
        D102: Missing docstring in public method
masonite/contracts/UploadContract.py:15 in public method `store`:
        D102: Missing docstring in public method
masonite/contracts/UploadContract.py:19 in public method `store_prepend`:
        D102: Missing docstring in public method
masonite/contracts/SessionContract.py:1 at module level:
        D100: Missing docstring in public module
masonite/contracts/SessionContract.py:7 in public method `get`:
        D102: Missing docstring in public method
masonite/contracts/SessionContract.py:11 in public method `set`:
        D102: Missing docstring in public method
masonite/contracts/SessionContract.py:15 in public method `has`:
        D102: Missing docstring in public method
masonite/contracts/SessionContract.py:19 in public method `all`:
        D102: Missing docstring in public method
masonite/contracts/SessionContract.py:23 in public method `delete`:
        D102: Missing docstring in public method
masonite/contracts/SessionContract.py:27 in public method `flash`:
        D102: Missing docstring in public method
masonite/contracts/SessionContract.py:31 in public method `reset`:
        D102: Missing docstring in public method
masonite/contracts/SessionContract.py:35 in public method `helper`:
        D102: Missing docstring in public method
masonite/contracts/BroadcastContract.py:1 at module level:
        D100: Missing docstring in public module
masonite/contracts/BroadcastContract.py:7 in public method `ssl`:
        D102: Missing docstring in public method
masonite/contracts/BroadcastContract.py:11 in public method `channel`:
        D102: Missing docstring in public method
masonite/contracts/__init__.py:1 at module level:
        D104: Missing docstring in public package
masonite/contracts/MailContract.py:1 at module level:
        D100: Missing docstring in public module
masonite/contracts/MailContract.py:7 in public method `to`:
        D102: Missing docstring in public method
masonite/contracts/MailContract.py:11 in public method `template`:
        D102: Missing docstring in public method
masonite/contracts/MailContract.py:15 in public method `send_from`:
        D102: Missing docstring in public method
masonite/contracts/MailContract.py:19 in public method `subject`:
        D102: Missing docstring in public method
masonite/contracts/QueueContract.py:1 at module level:
        D100: Missing docstring in public module
masonite/contracts/QueueContract.py:7 in public method `push`:
        D102: Missing docstring in public method
masonite/contracts/managers/SessionManagerContract.py:1 at module level:
        D100: Missing docstring in public module
masonite/contracts/managers/BroadcastManagerContract.py:1 at module level:
        D100: Missing docstring in public module
masonite/contracts/managers/CacheManagerContract.py:1 at module level:
        D100: Missing docstring in public module
masonite/contracts/managers/MailManagerContract.py:1 at module level:
        D100: Missing docstring in public module
masonite/contracts/managers/UploadManagerContract.py:1 at module level:
        D100: Missing docstring in public module
masonite/contracts/managers/QueueManagerContract.py:1 at module level:
        D100: Missing docstring in public module
masonite/testsuite/TestRequest.py:1 at module level:
        D100: Missing docstring in public module
masonite/testsuite/TestRequest.py:7 in public method `__init__`:
        D102: Missing docstring in public method
masonite/testsuite/TestRequest.py:11 in public method `get`:
        D102: Missing docstring in public method
masonite/testsuite/TestRequest.py:15 in public method `status_code`:
        D102: Missing docstring in public method
masonite/testsuite/TestRequest.py:21 in public method `contains`:
        D102: Missing docstring in public method
masonite/testsuite/__init__.py:1 at module level:
        D104: Missing docstring in public package
masonite/testsuite/TestRoute.py:1 at module level:
        D100: Missing docstring in public module
masonite/testsuite/TestRoute.py:7 in public method `__init__`:
        D102: Missing docstring in public method
masonite/testsuite/TestRoute.py:15 in public method `exists`:
        D102: Missing docstring in public method
masonite/testsuite/TestRoute.py:18 in public method `has_middleware`:
        D102: Missing docstring in public method
masonite/testsuite/TestSuite.py:1 at module level:
        D100: Missing docstring in public module
masonite/testsuite/TestSuite.py:9 in public function `generate_wsgi`:
        D103: Missing docstring in public function
masonite/testsuite/TestSuite.py:41 in public method `create_container`:
        D102: Missing docstring in public method
masonite/testsuite/TestSuite.py:108 in public method `get_container`:
        D102: Missing docstring in public method
masonite/testsuite/TestSuite.py:111 in public method `route`:
        D102: Missing docstring in public method
masonite/testsuite/TestSuite.py:114 in public method `get`:
        D102: Missing docstring in public method
masonite/providers/QueueProvider.py:14 in public method `register`:
        D102: Missing docstring in public method
masonite/providers/QueueProvider.py:19 in public method `boot`:
        D102: Missing docstring in public method
masonite/providers/WhitenoiseProvider.py:12 in public method `register`:
        D102: Missing docstring in public method
masonite/providers/AppProvider.py:26 in public method `register`:
        D102: Missing docstring in public method
masonite/providers/AppProvider.py:69 in public method `boot`:
        D102: Missing docstring in public method
masonite/providers/CsrfProvider.py:11 in public method `register`:
        D102: Missing docstring in public method
masonite/providers/CsrfProvider.py:14 in public method `boot`:
        D102: Missing docstring in public method
masonite/providers/__init__.py:1 at module level:
        D104: Missing docstring in public package
masonite/providers/ViewProvider.py:11 in public method `register`:
        D102: Missing docstring in public method
masonite/providers/ViewProvider.py:16 in public method `boot`:
        D102: Missing docstring in public method
masonite/providers/HelpersProvider.py:17 in public method `register`:
        D102: Missing docstring in public method
masonite/providers/SassProvider.py:20 in public method `boot`:
        D102: Missing docstring in public method
masonite/providers/MailProvider.py:14 in public method `register`:
        D102: Missing docstring in public method
masonite/providers/MailProvider.py:20 in public method `boot`:
        D102: Missing docstring in public method
masonite/providers/SessionProvider.py:14 in public method `register`:
        D102: Missing docstring in public method
masonite/providers/SessionProvider.py:20 in public method `boot`:
        D102: Missing docstring in public method
masonite/providers/BroadcastProvider.py:14 in public method `register`:
        D102: Missing docstring in public method
masonite/providers/BroadcastProvider.py:20 in public method `boot`:
        D102: Missing docstring in public method
masonite/providers/StatusCodeProvider.py:8 in public method `load`:
        D102: Missing docstring in public method
masonite/providers/StatusCodeProvider.py:28 in public method `register`:
        D102: Missing docstring in public method
masonite/providers/StatusCodeProvider.py:31 in public method `boot`:
        D102: Missing docstring in public method
masonite/providers/RouteProvider.py:11 in public method `register`:
        D102: Missing docstring in public method
masonite/providers/RouteProvider.py:14 in public method `boot`:
        D102: Missing docstring in public method
masonite/providers/StartResponseProvider.py:10 in public method `register`:
        D102: Missing docstring in public method
masonite/providers/StartResponseProvider.py:13 in public method `boot`:
        D102: Missing docstring in public method
masonite/providers/UploadProvider.py:16 in public method `register`:
        D102: Missing docstring in public method
masonite/providers/UploadProvider.py:22 in public method `boot`:
        D102: Missing docstring in public method
masonite/providers/CacheProvider.py:14 in public method `register`:
        D102: Missing docstring in public method
masonite/providers/CacheProvider.py:19 in public method `boot`:
        D102: Missing docstring in public method
masonite/managers/__init__.py:1 at module level:
        D104: Missing docstring in public package
masonite/testing/UnitTest.py:1 at module level:
        D100: Missing docstring in public module
masonite/testing/UnitTest.py:10 in public method `setup_method`:
        D102: Missing docstring in public method
masonite/testing/UnitTest.py:13 in public method `controller`:
        D102: Missing docstring in public method
masonite/testing/UnitTest.py:16 in public method `get`:
        D102: Missing docstring in public method
masonite/testing/UnitTest.py:22 in public method `route`:
        D102: Missing docstring in public method
masonite/testing/UnitTest.py:27 in public method `routes`:
        D102: Missing docstring in public method
masonite/testing/UnitTest.py:30 in public method `json`:
        D102: Missing docstring in public method
masonite/testing/MockJson.py:1 at module level:
        D100: Missing docstring in public module
masonite/testing/MockJson.py:7 in public method `__init__`:
        D102: Missing docstring in public method
masonite/testing/MockJson.py:11 in public method `json`:
        D102: Missing docstring in public method
masonite/testing/MockJson.py:16 in public method `contains`:
        D102: Missing docstring in public method
masonite/testing/MockRoute.py:1 at module level:
        D100: Missing docstring in public module
masonite/testing/MockRoute.py:10 in public method `__init__`:
        D102: Missing docstring in public method
masonite/testing/MockRoute.py:14 in public method `is_named`:
        D102: Missing docstring in public method
masonite/testing/MockRoute.py:17 in public method `has_middleware`:
        D102: Missing docstring in public method
masonite/testing/MockRoute.py:20 in public method `has_controller`:
        D102: Missing docstring in public method
masonite/testing/MockRoute.py:23 in public method `contains`:
        D102: Missing docstring in public method
masonite/testing/MockRoute.py:31 in public method `status`:
        D102: Missing docstring in public method
masonite/testing/MockRoute.py:42 in public method `ok`:
        D102: Missing docstring in public method
masonite/testing/MockRoute.py:45 in public method `can_view`:
        D102: Missing docstring in public method
masonite/testing/MockRoute.py:53 in public method `user`:
        D102: Missing docstring in public method
masonite/testing/MockRoute.py:58 in public method `is_post`:
        D102: Missing docstring in public method
masonite/testing/MockRoute.py:61 in public method `is_get`:
        D102: Missing docstring in public method
masonite/testing/MockRoute.py:64 in public method `is_put`:
        D102: Missing docstring in public method
masonite/testing/MockRoute.py:67 in public method `is_patch`:
        D102: Missing docstring in public method
masonite/testing/MockRoute.py:70 in public method `is_delete`:
        D102: Missing docstring in public method
masonite/testing/MockRoute.py:73 in public method `on_bind`:
        D102: Missing docstring in public method
masonite/testing/MockRoute.py:77 in public method `has_session`:
        D102: Missing docstring in public method
masonite/testing/MockRoute.py:84 in public method `session`:
        D102: Missing docstring in public method
masonite/testing/MockRoute.py:91 in public method `on_make`:
        D102: Missing docstring in public method
masonite/testing/MockRoute.py:95 in public method `on_resolve`:
        D102: Missing docstring in public method
masonite/testing/__init__.py:1 at module level:
        D104: Missing docstring in public package
masonite/testing/BaseRequest.py:1 at module level:
        D100: Missing docstring in public module
masonite/testing/BaseRequest.py:2 in public method `user`:
        D102: Missing docstring in public method
masonite/testing/BaseRequest.py:11 in public method `ok`:
        D102: Missing docstring in public method
masonite/testing/BaseRequest.py:14 in public method `status`:
        D102: Missing docstring in public method
masonite/testing/MockRequest.py:1 at module level:
        D100: Missing docstring in public module
masonite/testing/MockRequest.py:7 in public method `__init__`:
        D102: Missing docstring in public method
masonite/testing/MockController.py:1 at module level:
        D100: Missing docstring in public module
masonite/testing/MockController.py:3 in public method `returns_instance_of`:
        D102: Missing docstring in public method
masonite/queues/__init__.py:1 at module level:
        D104: Missing docstring in public package
masonite/commands/KeyCommand.py:14 in public method `handle`:
        D102: Missing docstring in public method
masonite/commands/TinkerCommand.py:21 in public method `handle`:
        D102: Missing docstring in public method
masonite/commands/MigrateRefreshCommand.py:13 in public method `handle`:
        D102: Missing docstring in public method
masonite/commands/BaseScaffoldCommand.py:1 at module level:
        D100: Missing docstring in public module
masonite/commands/BaseScaffoldCommand.py:21 in public method `handle`:
        D102: Missing docstring in public method
masonite/commands/MigrateStatusCommand.py:17 in public method `handle`:
        D102: Missing docstring in public method
masonite/commands/MigrateCommand.py:17 in public method `handle`:
        D102: Missing docstring in public method
masonite/commands/RoutesCommand.py:13 in public method `handle`:
        D102: Missing docstring in public method
masonite/commands/SeedRunCommand.py:16 in public method `handle`:
        D102: Missing docstring in public method
masonite/commands/SeedRunCommand.py:31 in public method `check_init_file`:
        D102: Missing docstring in public method
masonite/commands/__init__.py:1 at module level:
        D104: Missing docstring in public package
masonite/commands/InfoCommand.py:21 in public method `handle`:
        D102: Missing docstring in public method
masonite/commands/UpCommand.py:15 in public method `handle`:
        D102: Missing docstring in public method
masonite/commands/ViewCommand.py:15 in public method `handle`:
        D102: Missing docstring in public method
masonite/commands/InstallCommand.py:16 in public method `handle`:
        D102: Missing docstring in public method
masonite/commands/ServeCommand.py:22 in public method `handle`:
        D102: Missing docstring in public method
masonite/commands/ServeCommand.py:204 in public method `__init__`:
        D102: Missing docstring in public method
masonite/commands/ServeCommand.py:214 in public method `run`:
        D102: Missing docstring in public method
masonite/commands/ServeCommand.py:230 in public method `trigger_reload`:
        D102: Missing docstring in public method
masonite/commands/ServeCommand.py:234 in public method `log_reload`:
        D102: Missing docstring in public method
masonite/commands/ServeCommand.py:241 in public method `__init__`:
        D102: Missing docstring in public method
masonite/commands/ServeCommand.py:283 in public method `trigger_reload`:
        D102: Missing docstring in public method
masonite/commands/ServeCommand.py:290 in public method `run`:
        D102: Missing docstring in public method
masonite/commands/SeedCommand.py:16 in public method `handle`:
        D102: Missing docstring in public method
masonite/commands/SeedCommand.py:25 in public method `check_init_file`:
        D102: Missing docstring in public method
masonite/commands/AuthCommand.py:15 in public method `handle`:
        D102: Missing docstring in public method
masonite/commands/MigrateResetCommand.py:17 in public method `handle`:
        D102: Missing docstring in public method
masonite/commands/MakeMigrationCommand.py:17 in public method `handle`:
        D102: Missing docstring in public method
masonite/commands/DownCommand.py:13 in public method `handle`:
        D102: Missing docstring in public method
masonite/commands/ControllerCommand.py:19 in public method `handle`:
        D102: Missing docstring in public method
masonite/commands/MigrateRollbackCommand.py:16 in public method `handle`:
        D102: Missing docstring in public method
masonite/helpers/misc.py:21 in public function `dot`:
        D103: Missing docstring in public function
masonite/helpers/filesystem.py:1 at module level:
        D100: Missing docstring in public module
masonite/helpers/filesystem.py:4 in public function `make_directory`:
        D103: Missing docstring in public function
masonite/helpers/__init__.py:1 at module level:
        D104: Missing docstring in public package
masonite/helpers/status.py:68 in public function `response_statuses`:
        D103: Missing docstring in public function

**Comment by hammacktony** [comment]
Wow.

**Comment by hammacktony** [comment]
I take it I should branch off master?

**Comment by vaibhavmule** [comment]
@hammacktony 

Based off from `develop` branch, complete as much you can.

**Comment by S-M-Jawwad-Raza** [comment]
@hammacktony which ones are still left?

**Comment by hammacktony** [comment]
Testsuite and everything after it. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by hammacktony** [comment]
<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by hammacktony** [comment]
<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by josephmancuso** [comment]
let's close this and regenerate that list. Some of these are completed
