### ISSUE TITLE
it is hard to debug 500 Internal server error, it should show exception and traceback

### ISSUE THREAD

**Issue by vaibhavmule** [MasoniteFramework/core#452]
When `APP_DEBUG` is True, it should show exception and traceback, maybe even for 404, 503 pages.

![500 internal server error](https://user-images.githubusercontent.com/6290791/47131638-692cdd80-d2bd-11e8-8fd9-d2793b3f8e37.png)

**Comment by josephmancuso** [comment]
This 500 Server Error only shows when the `APP_DEBUG=False`. Is this also showing when it is `True`?

**Comment by vaibhavmule** [comment]
Sorry, I forgot to rename a file from `.env-example` to `.env`@josephmancuso
