### ISSUE TITLE
Handling 500 and 404 errors

### ISSUE THREAD

**Issue by hammacktony** [MasoniteFramework/core#466]
Although I appreciate the default exception handling of these errors, I would suggest the option to have the ability to turn off the custom/user error templates.

For json requests, I want to return specific response when a 500 or 404 are raised. Instead, I return an html page. 

I suggest something like: `Request.status("500 or 404", render=False)`.

**Comment by josephmancuso** [comment]
what are you thinking of returning? A json response?

**Comment by hammacktony** [comment]
Yeah. I want to return a json response. Personally. 

I think default to html is nice. But have it hidden away somewhere a method to return Jason. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by hammacktony** [comment]
Sorry. I’m on my phone. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by josephmancuso** [comment]
hmm thinking of how to make this pretty. What you could do is have a ServiceProvider that runs after the RouteProvider which will check if the request status will be a 404 and makes the response a JSON response

**Comment by hammacktony** [comment]
Hmm. Maybe it’s my naïveté, but why does it “automatically “ view the 500.html? Shouldn’t it respond with 500 then after that, if the option is true, render the html? 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by hammacktony** [comment]
Capture the response first...then load if possible.

Doesn’t that make most sense? 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by josephmancuso** [comment]
ok so in order to do this currently you will need to do something like:

```python
""" A JsonResponseProvider Service Provider """

from masonite.provider import ServiceProvider
from masonite.request import Request
from masonite.view import View
import json


class JsonResponseProvider(ServiceProvider):
    """Provides Services To The Service Container
    """

    wsgi = True
    
    def register(self):
        """Register objects into the Service Container
        """
        
        pass

    def boot(self, request: Request, view: View):
        """Boots services required by the container
        """
        
        request.header('Content-Type', 'application/json')

        if request.is_status(404):
            self.app.bind('Response', json.dumps({'status': 'Not Found'}))
        elif request.is_status(500):
            self.app.bind('Response', json.dumps({'status': 'There is an error'}))
        
        request.header('Content-Length', str(len(self.app.make('Response'))))      

```

the `request.is_status()` is a 2.1 method so you will need to do:

```
 if request.get_status_code() == '404 Not Found':
```

**Comment by josephmancuso** [comment]
it will be a service provider obviously

**Comment by josephmancuso** [comment]
I am thinking of making a response object in here 🤔

**Comment by josephmancuso** [comment]
also if you don't want to default status code stuff to show then remove the `StatusCodeProvider`
