### ISSUE TITLE
Handling Requests of Different Methods

### ISSUE THREAD

**Issue by hammacktony** [MasoniteFramework/core#467]
If I try `Post` method on a route that has `Get`, I get a TypeError. Which, is what I am supposed to get. However, I propose we have a more specific error. It should return a `405 Method Not Allowed` when I try a non-supported method.

**Comment by hammacktony** [comment]
It is thrown in `request.py`

```
def _set_standardized_request_variables(self, variables):
        """The input data is not perfect so we have to standardize it into a dictionary.

        Arguments:
            variables {string|dict}
        """
        if isinstance(variables, str):
            variables = parse_qs(variables)

        try:
            for name in variables.keys():
                value = self._get_standardized_value(variables[name])
                self.request_variables[name.replace('[]', '')] = value
        except TypeError:
            self.request_variables = {}
```

**Comment by josephmancuso** [comment]
I don't think this is correct 🤔 

If you try a POST method on a route that has GET you will (and should) get a 404 response. The TypeError you posted is never thrown. It is handled by setting the inputs to a blank dictionary. These are used for the `request.input('')` stuff

**Comment by hammacktony** [comment]
I tried it with Postman. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by josephmancuso** [comment]
oh right well you should get a 500 because there is no response so postman will throw it's own 500.

**Comment by josephmancuso** [comment]
although it should have some kind of response ...... let me look into this

**Comment by josephmancuso** [comment]
note to self: This should be able to be able to be done in the new response middleware
