### ISSUE TITLE
View routes for static pages

### ISSUE THREAD

**Issue by nioperas06** [MasoniteFramework/core#471]
References: 
[AdonisJS](https://adonisjs.com/docs/4.1/routing)
```js
// resources/view/welcome.edge
Route.on('/').render('welcome')
```
[Laravel](https://laravel.com/docs/5.7/routing#view-routes)
```php
Route::view('/welcome', 'welcome');
```

**Comment by josephmancuso** [comment]
This will exist in 2.1 and is already done :)
