### ISSUE TITLE
Add Mising Docstring for Masonite Repo.

### ISSUE THREAD

**Issue by vaibhavmule** [MasoniteFramework/core#474]
Here is [Masonite Repo](https://github.com/MasoniteFramework/masonite).

./databases/migrations/__init__.py:1 at module level:
        D104: Missing docstring in public package
./databases/migrations/2018_01_09_043202_create_users_table.py:1 at module level:
        D100: Missing docstring in public module
./databases/migrations/2018_01_09_043202_create_users_table.py:4 in public class `CreateUsersTable`:
        D101: Missing docstring in public class
./databases/seeds/__init__.py:1 at module level:
        D104: Missing docstring in public package
./databases/seeds/database_seeder.py:6 in public class `DatabaseSeeder`:
        D101: Missing docstring in public class
./resources/__init__.py:1 at module level:
        D104: Missing docstring in public package
./resources/templates/__init__.py:1 at module level:
        D104: Missing docstring in public package
./storage/uploads/__init__.py:1 at module level:
        D104: Missing docstring in public package
./storage/static/__init__.py:1 at module level:
        D104: Missing docstring in public package

**Comment by josephmancuso** [comment]
completed. I don't think we should put docstrings on the seeders since the generated seeders don't have docstrings
