### ISSUE TITLE
Rethink Directory Structure for Masonite

### ISSUE THREAD

**Issue by vaibhavmule** [MasoniteFramework/core#477]
Current Directory Structure for https://github.com/MasoniteFramework/masonite

I personally feel that the following folder are redundant.  I would like to propose to remove it.

- Remove `http` folder and move controllers and middleware to `app` folder
- Remove `resources` folder and move templates folder to `app` folder
- Remove `routes` folder and move `web.py` to as `routes.py` to `app` folder.

This is how it will look like: https://github.com/vaibhavmule/masonite/tree/rethink-dir

**Comment by josephmancuso** [comment]
Besides the first one with the controlllers in the Http folder, you can add templates to your app directory if you want and add that environment to the view class in a service provider as well as create a routes.py anywhere in your project and import it into the web.py file. 

but I understand your point about changing the defaults to a different layout

**Comment by josephmancuso** [comment]
You could technically actually place your controllers anywhere and import them directly into your web.py file. They are not constricted to only be in that folder

**Comment by vaibhavmule** [comment]
Giving an ability to restructure the application themselves is a good idea, but having a convention over is good. As if you want to look at someone else code, you know where things are. same with python as language, it complies with indentation so much that, most of the code looks same and friendly.

**Comment by josephmancuso** [comment]
right. I think changing directory structure is too big a leap for a major release even if it's easy to upgrade. I deff think we should do this but not right now for 2.1 or even 2.2. We will need to discuss after 2.1 if we will continue with the 2.x release or move to a 3.x

**Comment by vaibhavmule** [comment]
Yes, I do agree. 

But yeah, it is Nice to discuss this.

**Comment by josephmancuso** [comment]
i'll close this for now but let's revisit this when time comes

**Comment by clsource** [comment]
Another argument for keeping things as now is that having the current directory structure is similar to Laravel's. So that would help newcomers that comes from Laravel and try masonite 👍

**Comment by vaibhavmule** [comment]
@clsource

I do agree with you but we should have things which are Masonite, so that they will learn new things about Masonite. 

Building an identical framework is good idea and we are doing that pretty much with adding lots of things from Laravel but Masonite should have its our own idea for to solve problem.
