### ISSUE TITLE
Add "Mailable" classes.

### ISSUE THREAD

**Issue by josephmancuso** [MasoniteFramework/core#511]
These are classes that can be used to encompass full messages that look something like:

```python
class OrderMailable(Mailable):

    def __init__(self, email):
        self.email = email

    def handle(self):
        return self.subject('This is a subject') \
            .template('some.template') \
            .to(self.email) \
            .from('Customer Service')
```

and then you should be able to pass it via the send method:

```python
def show(self, mail: Mail):
    mail.send(OrderMailable('arg1', 'arg2'))
```

**Comment by vaibhavmule** [comment]
Is this related to this issue, https://github.com/MasoniteFramework/core/issues/496?

**Comment by josephmancuso** [comment]
it can be. Seperate features (one is python classes, one will be jinja2 macros)
