### ISSUE TITLE
Add Sessions

### ISSUE THREAD

**Issue by josephmancuso** [MasoniteFramework/core#52]
Since the request is technically a singleton throughout the life of the server (it is instantiated before the server is started) we can technically have sessions. We would need to create a `session()` method on the request class which will generate a `_session` attribute on the request class that might look something like:

```python

_session = {
    '28.029.291.199': {
        'username': 'Joseph'
    }
}
```

Then we can use something like:

```python
# sets the session variable
Request.session('username', 'Mike')
```

or just use:

```python
# sets the session variable
Request.session('username')
# Returns Mike
```

I have to make sure that somehow this is secure. Using an IP address might actually be insecure because it might be able to be spoofed and now we have cross session access. I'll need a way to somehow ensure that WSGI doesn't allow a way to set the REMOTE_ADDR as an environ variable (I think that even if one is sent it will be converted to HTTP_REMOTE_ADDR) so it should be fine. There is something called `X-HTTP-FORWARDED-FOR`. Might need to check that.

https://stackoverflow.com/questions/7835030/obtaining-client-ip-address-from-a-wsgi-app-using-eventlet?lq=1

This should also be it's own class and the request class should inherit it. Call the class `Session` which should not be able to be instantiated directly (and abstract class). Put this class inside a new file inside the base of the project called `session.py`. So this should be inside `masonite/session.py` and put the class Session inside of that.

Then import it into the request.py and inherit the Request class from it.

@mapeveri Is this something you'd want to do? It's pretty straight forward.

**Comment by mapeveri** [comment]
@josephmancuso Yes, I think a time to do it. One thing, I would like the methods to be 'set' and 'get' to set and get the session. What do you think?

**Comment by josephmancuso** [comment]
so a `set_session` and `get_session`. Although it "looks" like it's more explicit and easier to understand what's happening, I'm not entirely sure that adds any value over the normal way.

I'm not a huge fan of `get_` and `set_` the two methods. I like it when it's not going to be primarily developer facing. For example if it's just an internal method that we use for `core` only. If it's going to be front facing I'd like it to be as clean as possible.

If you'd like to know how to implement the one parameter get and 2 parameter set then look at the new `header()` method on the Request class.

**Comment by josephmancuso** [comment]
It's kind of a random thought I had when making the `header` method (the 1 method 2 parameter thing). Maybe we'll change it for Masonite 1.6 but let's go with that for now. It is very opinionated I know lol but we're taking a gamble on it :)

**Comment by mapeveri** [comment]
I say something like that:

```
Request.session.set('username', 'Mike')

Request.session.get('username')
```

**Comment by josephmancuso** [comment]
Ummm ok we can go with that. We'll have to do something like this then:

```python
class Request:

    def __init__(self):
        ...
        self.session = Session()
    
```

**Comment by mapeveri** [comment]
Exactly!

**Comment by josephmancuso** [comment]
It serves the same purpose for extracting out the session from the class so I'm for it. I'm slightly on the fence about it because header is different now. But Masonite 1.6 (releasing in May) is going to focus only on polishing. So no major feature improvement, only fine tuning the API we have now. So if we need to change the header or the session then we can.

**Comment by josephmancuso** [comment]
The Request class is too big for my liking so we'll modularize it as we move forward and add new features to it

**Comment by mapeveri** [comment]
Yes, more modularization would be excellent :)

**Comment by josephmancuso** [comment]
Also people can add new sessions by simply creating a service provider and doing something like:

```python
...

    def register(self):
        self.app.make('Request').session = SomeNewTypeOfSessionClass()
```

so it will be swappable instead of inheriting from a class which is a concrete implementation. 

Good call! 👍 🥇

**Comment by josephmancuso** [comment]
you know what, take two more medals 🥇 🥇

**Comment by mapeveri** [comment]
ahahahah awesome :+1:

**Comment by josephmancuso** [comment]
Masonite 1.6 will now be `Request.headers.set()` etc to make that more modular too.

**Comment by josephmancuso** [comment]
The headers won't actually have to be swappable because I mean, there is only 1 type of implementation for headers, can't really mess it up but it will need to be changed anyway to resemble this new session implementation

**Comment by josephmancuso** [comment]
I keep thinking about this now lol. In the future (1.6, deff not 1.5) but we will add a `session.py` configuration and create drivers. Some people may want a normal `memory` session, some may want all sessions as cookies or all sessions as `redis` or something:

```
DRIVER = 'cookie'
```

which will have the same exact design pattern as all the other managers:

```python
...
def register(self):
    self.app.bind('CookieSessionDriver', CookieSessionDriver)
    self.app.make('Request').session = SessionManager()
```

Let this be for Masonite 1.6 if you don't want to make it for Masonite 1.5

**Comment by mapeveri** [comment]
Yes, we start with the basics. I now create an issue to handle drivers with the sessions.

**Comment by josephmancuso** [comment]
@mapeveri Hey let's also add a `session.reset()` which should remove all session data (reset the session to an empty dictionary)
