### ISSUE TITLE
Should we be able to config timezone on config vars?

### ISSUE THREAD

**Issue by rfschubert** [MasoniteFramework/core#526]
Maybe we can discuss a bit more, but one global var to config `datetime` on Masonite could be useful.

Django has an `TIME_ZONE` global var on `config.py` and it helps a lot.
But Models in Django are integrated, on Masonite is not... or just a global config on Orator inside Masonite.

**Comment by josephmancuso** [comment]
been thinking about this 🤔 .. I think the best way to do is to specify it on the model level:

according to this PR: https://github.com/sdispater/orator/issues/83

We can do something like:

```python
    @accessor
    def created_at(self):
        return pendulum.parse(self._attributes['created_at'], tz=config('application.timezone'))
```

or something. You can even make this a parent class:

```python
class UsesTimezone:

    @accessor
    def created_at(self):
        return pendulum.parse(self._attributes['created_at'], tz=config('application.timezone'))
```

and put it on your model:

```
from app.helpers import UsesTimezone

class User(Model, UsesTimezone):
    ...
```

Masonite 2.2 will move this `Model` class into core so we can make cool helpers like that with new releases. Currently `Model` points to the value inside the `config/database.py` file.

Gonna close for now and relook at this when we start developing 2.2 next month
