### ISSUE TITLE
Create drivers for sessions

### ISSUE THREAD

**Issue by mapeveri** [MasoniteFramework/core#53]
This issue depends on #52. What is needed is to add drivers to store the sessions, for example Redis, etc.

**Comment by mapeveri** [comment]
I will see about making this issue.

**Comment by josephmancuso** [comment]
Great this should be fairly simple. Just take all of the logic of the session and make it a `memory` driver. Then you'll have to make a `config/session.py` file where we can put our driver configuration files

**Comment by mapeveri** [comment]
Please gitter ;)
