### ISSUE TITLE
Add a check for unmigrated migrations

### ISSUE THREAD

**Issue by josephmancuso** [MasoniteFramework/core#530]
When you first run `craft serve -r` or `craft serve` you should be notified if you don't have a migration migrated

**Comment by bjorntheart** [comment]
I guessing that would involved something like the following

1. query the migrations table and get the name of the last migration
2. get a directory listing of the migrations.
3. match the last migration value from 1. to the last entry in the directory listing
4. If it doesn't match slice the directory listing list from the index found matching the last migration from 1
5. Print results to stdout
6. Do happy dance 🕺

**Comment by josephmancuso** [comment]
@bjorntheart umm maybe lmao. @rickwest i believe is the one who implemented the `migrate:status` command so this feature would really just involve porting that code over and if it finds a match of "No" than just output a command line of like "You have unmigrated migrations. run `craft migrate` to migrate them." or something.
