### ISSUE TITLE
start supporting new authentication drivers

### ISSUE THREAD

**Issue by josephmancuso** [MasoniteFramework/core#537]
currently we have 1 way to authenticate which is to bascially store a normal cookie with the remember token and then authenticate it against the database but there should be other ways to do it as this means at least 1 database call per request

**Comment by rfschubert** [comment]
We can create a JWT auth, it will allow secure share tokens between server and user without database calls

**Comment by josephmancuso** [comment]
yeah this is going to need a bit of a rework. We currently don't have any concept of authentication drivers, everything is a bit hardcoded to use cookies right now.

We should be able to do both:

1. cookie
2. database based
3. jwt

As well as allow others to write their own authentication drivers

**Comment by josephmancuso** [comment]
this is done. Added a new jwt driver
