### ISSUE TITLE
Experiment with the idea of optionally adding parameters into the controller method

### ISSUE THREAD

**Issue by josephmancuso** [MasoniteFramework/core#542]
## Voting Issue

This is an experimental suggestion. Please vote 👍 or 👎 

It might be a good idea that instead of doing this:

```python
# /dashboard/user/@id
# /dashboard/user/1
def show(self, request: Request):
    param = request.param('id') #== 1
```

we should instead be able to do:

```python
# /dashboard/user/@id
# /dashboard/user/1
def show(self, id):
    id #== 1
```

and it should also be able to resolve multiple (out of order) like this:

```python
# /dashboard/user/@id
# /dashboard/user/1
def show(self, upload: Upload, id, mail: Mail):
    id #== 1
    upload #== <masonite.Upload>
    mail #== <masonite.Mail>
```

This will condense a method down from this:

```python
    def sites(self, request: Request):
        return Site.where('user_id', request.param('user_id')).get().serialize()
```

to this:

```python
    def sites(self, user_id):
        return Site.where('user_id', user_id).get().serialize()
```

This is really just a 1 line addition so it is not very hard to implement. This will only be used for controller methods.

Please vote 👍 on this comment if you approve or 👎 if you disapprove

**Comment by josephmancuso** [comment]
We'll need to change this line: https://github.com/MasoniteFramework/core/blob/76a43dc522beb9f9ae576cad27fe0782f5f1910d/masonite/routes.py#L212

to be something like:

```
controller = self.request.app().resolve(self.controller, **self.request.url_params)
```

**Comment by hammacktony** [comment]
To follow normal function conventions, the format should be:

```
def show(self, id, upload: Upload, mail: Mail):
```

**Comment by hammacktony** [comment]
`func(*args, **kwargs`

**Comment by josephmancuso** [comment]
yeah. Well the resolve method actually works interchangably. So whatever order you want to add it is up to you. and the `(self, id, upload: Upload, mail: Mail):` are all technically `*args` but i do agree that in the docs we should put all instances of request parameters to the front

**Comment by bjorntheart** [comment]
❤️  this @josephmancuso. 👍 up from me

**Comment by rfschubert** [comment]
Just 👍 if we still be able to use `request.input()` :)

**Comment by josephmancuso** [comment]
@rfschubert yeah it would be fully backwards compatible. I'm gonna experiment with my software and see if theres any issues

**Comment by josephmancuso** [comment]
In develop branch
