### ISSUE TITLE
Change how route classes are constructed

### ISSUE THREAD

**Issue by josephmancuso** [MasoniteFramework/core#555]
Currently we have something like this:

```python
Get().route('/route', 'Controller@show').middleware(..)..
```

but it really should be:

```python
Get('/route', 'Controller@show').middleware(..)..
```

This should be backwards compatible. For example the constructor of `Get()` should be:

```python
def __init__(self, route, controller):
    self.route(route, controller)
```

but it just seems odd to declare `Get().route(..)` and not `Get(..)`

**Comment by vaibhavmule** [comment]
I think this is more similar to helpers functions `get()`,  `post()` I loved them, yeah `.route()` felt redundant.

**Comment by josephmancuso** [comment]
This actually is going into the next minor
