### ISSUE TITLE
Add a register method to the authentication class

### ISSUE THREAD

**Issue by josephmancuso** [MasoniteFramework/core#557]
we need to keep abstracted as much as possible back into the framework. For 2.1 we abstracted a lot out like the CSRF middleware which now inherits a class rather than being a standalone class.

In the `RegisterController` when `craft auth` is ran, it will generate some code related to registering new users like running a create method on the authentication class but I think we need to abstract that out.

So we need to create a new register method which should accept a dictionary of values. Something like:

```
Auth(request).register({'name': 'Joe', 'email': 'email.com', 'password': 'pass123'})
```

This will allow us to change anything related to registering new users in future releases.

**Comment by vaibhavmule** [comment]
the `register`  method is good, but what if I want to save more field, are we calling this like this.

```
def register(self, user):
 ...
 auth.AUTH['model'].create(**user )
```

**Comment by josephmancuso** [comment]
yes we'll have to use it like that once implemented
