### ISSUE TITLE
look back into use of logging packages

### ISSUE THREAD

**Issue by josephmancuso** [MasoniteFramework/core#560]

**Comment by josephmancuso** [comment]
yeah i'm not sure what we want to do yet with it. I would like to create some kind of Masonite wrapper around it to make it as simple and powerful as possible ..

I'm actually at a roadblock with the queue stuff in #563 because we need a few more features in the queue feature in order to make it more modular. For example we need to:

* be able to support more queue drivers by adding them as a service provider (technically not possible without adding a new special run command as well)
* handle failed jobs (also not currently possible)

So i am introducing a rework to fix these issues (and create a way to make it extendable and modular at the same time) and not sure if a logger would solve the issue of failed jobs too 🤔 

It would be good to log that they ran but what about fetching failed jobs and trying them again?

**Comment by bjorntheart** [comment]
I don’t think a logger will solve the failed jobs scenario. 

This ticket kind of feel like part of it should be split off into an issue that deals with failed queue jobs. 
Storing failed jobs in the database makes sense, but I wonder if this could work with other queue drivers to? I don’t know enough about queues to have a clear answer for that 🤷‍♂️ If it doesn’t, then just throwing a failed job back onto the queue makes sense, but I think retry attempts should be limited

**Comment by hammacktony** [comment]
At one time, we used Mongo at work to log failed queues.

**Comment by josephmancuso** [comment]
## Drivers

- [ ] Papertrail
- [ ] Disk
- [ ] Sentry
- [ ] Stack Driver
- [ ] Slack driver
- [ ] A custom way to create your own drivers

## Implementation

Each logger driver should be able to handle 2 things: exceptions and normal messages. Even if one of the drivers can't handle one.

For example a Sentry driver probably can't handle normal log messages so it should just be disposed of but it can handle exceptions so it should handle them. If that makes sense.

Each driver should also have a name attached to it so it will create things like `<app-name>-log-2019-06-12`

### Stacks

There should also be stacks for when you want to do the same thing for multiple drivers. For example you might want to send error logs to both a local disk, papertrail and sentry:

```
DRIVER = 'all'

DRIVERS = {
  'all': {
    'driver': 'stack',
    'name': 'masonite',
    'drivers': [
        'papertrail',
        'disk',
        'sentry'
    ]
   }
}
```

**Comment by josephmancuso** [comment]
This is being worked on now over here https://github.com/MasoniteFramework/logging
