### ISSUE TITLE
Add better 404 exception handling.

### ISSUE THREAD

**Issue by josephmancuso** [MasoniteFramework/core#570]
Currently in development it just throws a 404 not found response. We need it to show a good exception handling message on why it could be that the 404 was thrown

**Comment by vaibhavmule** [comment]
Also when creating apis,  it should return 404 with empty body... 

I feel we shouldn't have 404 handling by default but allow an ability to add custom or built in pages on demand.

**Comment by vaibhavmule** [comment]
Looks like what I was asking done in https://github.com/MasoniteFramework/core/pull/631

**Comment by nioperas06** [comment]
Hum 🤔 is it related to something like `abort(404)` in Laravel? https://laravel.com/docs/5.8/errors#http-exceptions

**Comment by josephmancuso** [comment]
not going to put this in 2.2 until further discussions can be made. This can also be a 2.2 minor release
