### ISSUE TITLE
File URL of an uploaded file

### ISSUE THREAD

**Issue by nioperas06** [MasoniteFramework/core#571]
`url` method to get the URL for an uploaded file. 
```
upload.driver('disk').store(request.input('file_upload'))
#== '838nd92920sjsn928snaj92gj.png'

upload.driver('disk').url('838nd92920sjsn928snaj92gj.png')
#== 'https://localhost:8000/uploads/838nd92920sjsn928snaj92gj.png'
```
Adding a symbolic link between `storage/uploads` and `static/uploads` 🤔

**Comment by nioperas06** [comment]
Yes, 🤔 I do not think we really need this.

**Comment by nioperas06** [comment]
`delete` too.
```
upload.driver('disk').delete('838nd92920sjsn928snaj92gj.png')
```

**Comment by josephmancuso** [comment]
does this solve your use case? 🤔 https://docs.masoniteproject.com/the-basics/static-files#static-template-function

**Comment by josephmancuso** [comment]
you can use this same functionality outside of views by doing `from masonite.helpers import static`

**Comment by nioperas06** [comment]
Got it! To make them accessible from the web?
