### ISSUE TITLE
Request based form validation, à la Laravel

### ISSUE THREAD

**Issue by nioperas06** [MasoniteFramework/core#573]
Actually we have something like this:

```
""" A StoreRequest Validator """

from masonite.validator import Validator
from validator import Required

class StoreRequest(Validator):

    def perform_validate(self):
        self.validate({
            'title': [Required],
        })
```
```
from app.validators.Todo.StoreRequest import StoreRequest

class TodoController:

    def store(self, request: Request):
            validate = StoreRequest(request).perform_validate()
            if validate.check():
                   Todo.create(
                          'name' => request.input('name')
                   )
            
```
Thinkink about something like this 🤔 

```
""" A StoreRequest Validator """

from masonite.validator import Validator
from validator import Required

class StoreRequest(Validator):

    def rules(self):
        self.validate({
            'title': [Required],
        })
```
```
from app.validators.Todo.StoreRequest import StoreRequest

class TodoController:

    def store(self, request: StoreRequest):
            Todo.create(
                  'name' => request.input('name')
            )
            
```
This is one way to handle request validation in Laravel. By using `request: StoreRequest` this will validate `request` object according to `rules` and returned back to previous url when validation is wrong.

**Comment by josephmancuso** [comment]
i think the issue with redirecting back is we technically don't know what endpoint they came from because every request is stateless for the most part

**Comment by josephmancuso** [comment]
in theory we could set sessions as a cookie on the user and track things from request to request. Something like

```
'last-request': '/endpoint/1'
'current-request': 'endpoint/2'
```

and then redirect them back to the last request

**Comment by nioperas06** [comment]
like the `validate` inside routes file too 👍

**Comment by rfschubert** [comment]
> hmm. random thought i had when looking at this but what about something like:
> 
> ```python
> from app.validators import StoreValidation
> 
> ROUTES = [
>     get(..).middleware(..,..).validate(StoreValidation)
> ]
> ```
> 
> ?

This is good for the `API` package, but I think is not so useful with normal requests.
But maybe is not easy to add this directly to the model or object we want to validate?

Think about this scenario:

I want to add a User and his Address but I store it as 2 separated models.

I'll post something like this:
```JSON
{
    "username": "Jon Doe",
    "email": "jon@doe.com",
    "address": {
        "city": "New York",
        "state": "NY",
        "country": "USA"
    },
}
```

How my middleware will know it needs to validate both? But if I config on the model, it can first try to validate and then execute the query.

**Comment by josephmancuso** [comment]
this is done with the new 2.2 validation code
