### ISSUE TITLE
Add a Storage class

### ISSUE THREAD

**Issue by josephmancuso** [MasoniteFramework/core#586]
We need to create a `Storage` or `FileManagement` class or something to handle manipulating files and stuff. I'm not too much of a fan of making the upload drivers responsible for file management.
 
This would solve issues these better:

* https://github.com/MasoniteFramework/core/issues/572

* https://github.com/MasoniteFramework/core/issues/571

**Comment by Marlysson** [comment]
Will then the `UploadDriver` just call by delegation the `Storage` class?

**Comment by josephmancuso** [comment]
yes. I'm thinking something like an `S3` storage driver maybe? Or maybe turning the upload drivers into storage drivers for 2.2? This way it's more general?

This PR should be a place of discussion so any thoughts are welcome
