### ISSUE TITLE
Easier way to set status code

### ISSUE THREAD

**Issue by hammacktony** [MasoniteFramework/core#592]
Right now, we set the status code by `request.status_code(###)` in the controller. This does feel clunky. The more I think about it, the more I really think we should implement something like 
```return view('page.html'), 201```. 

Doing,

```
`request.status_code(###)` 

return view('blah')
```

is very cumbersome.

We can also set it in the `view` method. Either way, I think this change could really help devs out. It is just simple.

**Comment by hammacktony** [comment]
I know there have been talks on Github and Slack about a proposed change and it has been shot down. I really think we should look into this more.

**Comment by josephmancuso** [comment]
love the idea. what operator should set the status code? https://www.programiz.com/python-programming/operators

we can choose pretty much any one of these

**Comment by josephmancuso** [comment]
some ideas of what it would look like:

```python
return view.render('some.view', {'key': 'value'}) >> 200

return view.render('some.view', {'key': 'value'}) ^ 200

return view.render('some.view', {'key': 'value'}) ^= 200
```

**Comment by josephmancuso** [comment]
other possible choices:

```python
return view.render('some.view', {'key': 'value'}) @ 200

return view.render('some.view', {'key': 'value'}) & 200
```

**Comment by hammacktony** [comment]
`&` or `>>`

**Comment by hammacktony** [comment]
No one likes `@`.

**Comment by rfschubert** [comment]
I think the `>>` is way more concise

**Comment by josephmancuso** [comment]
going to close this issue. I'm not a huge fan of the inconsistency this will cause. For example, we can do something like:

```python
return view.render('some.template') >> 200
```

but we won't be able to do:

```python
return {'key': 'value'} >> 200
```

or 

```python
return Model.find(2) >> 200
```

because this will need to be overwritten in every single one of these class and `{dictionary} >> 200` is not valid Python syntax.
