### ISSUE TITLE
Add times to queues

### ISSUE THREAD

**Issue by josephmancuso** [MasoniteFramework/core#599]
We should be able to set a time in the future when a queue job should run.

we should be able to do something like:

```python
queue.push(SomeJob, args=(var1, var2), run_in='5 minutes')
```

or something like that.

All this would do is add a timestamp to the serialized job and then on the backend it will read that serialized job and only execute it if it is time to execute it.

Then we can do something even cooler if we want which is running a job continuously. This can be set on the job itself:

```python
class SomeJob:
    run_every = '5 minutes'
```

This will run the job when it is time to do so but then put it back into the queue for another 5 minute wait.

This would be useful for running something like checking if a new user has signed up and send them an email or anything else that Task Scheduling would require but inside a queue job instead.

The second option is just sugar but the first option is a must i think.

**Comment by hammacktony** [comment]
So, what is the difference between this and the `scheduler`? Couldn't we just use the scheduler to run a queue?

**Comment by josephmancuso** [comment]
yeah it would be really simliar except scheduler requires you to have a cron running on the server. It really only makes sense to do the second one because .. well .. it's like 2 lines of code away after coding the first thing lol
