### ISSUE TITLE
API Resource Middleware

### ISSUE THREAD

**Issue by hammacktony** [MasoniteFramework/core#616]
Need either an easier way to add middleware on a resource or have it better documented. You can overwrite `list_middleware` in the resource. You can also wrap the resource in a routegroup aand then apply it. I think we just need to keep it consistent with the normal routes. 

I think we can keep the `list_middleware` in the resource, because that might be handy. But, I think each resource should already be wrapped in a Route Group. So `BlahResource('blah').routes()` should return a Route Group and not a list.

This will make it more resources more inline with the normal ways routes are done.

**Comment by josephmancuso** [comment]
https://docs.masoniteproject.com/~/drafts/-L_Z4nljSTiAJpsnKxW4/primary/official-packages/masonite-api#adding-middleware
