### ISSUE TITLE
Craft Dev Commands

### ISSUE THREAD

**Issue by hammacktony** [MasoniteFramework/core#617]
I propose a new craft command called `test`. Running tests with `pytest` is simple enough. But, I see many PRs fail due to `flake8` errors. So, why not create a convenience command that runs both. It will simulate what Travis does.

**Comment by vaibhavmule** [comment]
This is a good idea, even before doing PR we can just run the command and raise PR error-free. 

I'm not sure, but I feel this should not in `craft` as it is `core` repo specific use case.

**Comment by hammacktony** [comment]
I wasn't too sure where to post this issue because it could have been in either place.

I know `tox` could do this, but I feel that is overkill.

**Comment by vaibhavmule** [comment]
I haven't work with `tox` much. We can use `makefile` too, and use those command in Travis too.

**Comment by hammacktony** [comment]
great idea

**Comment by kentaro0919** [comment]
I think "craft" is used in 2 ways. One from masonite_cli and the other from the project. I like to have project craft command to generate test.py files. And a wrapper command ``` $ python -m pytest``` for masonite_cli.

**Comment by hammacktony** [comment]
Its not just the wrapper for the test commands. I forget to run `flake8`. And I have my PRs fail over things I should have fixed. When I look at a lot of others PRs that fail, they have those issues. If we can replicate (as much as we can), then our local dev experience will be smoother.

**Comment by josephmancuso** [comment]
completely agree on all this

**Comment by vaibhavmule** [comment]
Note: This is done but @kentaro0919 commented about a wrapper command over `python -m pytest` is still pending.
