### ISSUE TITLE
Allow user to define output of 404 and 500 status codes

### ISSUE THREAD

**Issue by hammacktony** [MasoniteFramework/core#622]
This issue is addresses how when you set either a 404 or 500 status code, you get the automatic html response. This is fine for frontend dev, but not good for api development. I want to set either a 404 and 500, and give a custom response. 

I think I have asked this before in Slack. I cannot remember if we have already addressed this.

**Comment by vaibhavmule** [comment]
+1 for this as I feel this should be configurable!

**Comment by josephmancuso** [comment]
wait .. i just realized .. this is possible for views. But not yet for json so i'll keep this open.

I coded this when i coded the exception stuff. 

https://github.com/MasoniteFramework/core/blob/2.1/masonite/providers/StatusCodeProvider.py#L10-L23

**Comment by josephmancuso** [comment]
notice how it first checks for a `errors/xxx` template in your project and renders that if it exists. Else it will render the Masonite provided one.

**Comment by hammacktony** [comment]
Yeah. I was referring to json

**Comment by josephmancuso** [comment]
@MasoniteFramework/maintainers anybody have any ideas on how we should go about this? we basically just need to change what is displayed in the exception handler but how should this be configurable?

**Comment by josephmancuso** [comment]
if we made this a middleware ... We could then do something like this in the routes:

```python
ROUTES = [
    Get(..).middleware('exception:json')
]
```

**Comment by josephmancuso** [comment]
talking to @hammacktony we could just look at the headers ... duh .. if the headers is `application/json` then output a json response

**Comment by vaibhavmule** [comment]
I do not like this approach of checking data type, but also I do not have a solution for this at the moment!
