### ISSUE TITLE
Support more HTTP verbs

### ISSUE THREAD

**Issue by hammacktony** [MasoniteFramework/core#623]
I believe we should support more verbs. To be complete, we should support all http verb specs detailed in Mozilla docs (since Mozilla specs are essentially the standard).

https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods

**Comment by kentaro0919** [comment]
The link has the following verbs.

verbs | Supported status
------------ | -------------
GET | class Get(BaseHttpRoute):
HEAD | ?
POST | class Post(BaseHttpRoute)
PUT | class Put(BaseHttpRoute)
DELETE | class Delete(BaseHttpRoute)
CONNECT | ?
OPTIONS | ?
TRACE | ?
PATCH | class Patch(BaseHttpRoute)

**Comment by josephmancuso** [comment]
Sure! seems easy enough. this would just involve new classes, inheriting the `BaseHttpRoute` class and then changing the method type.

**Comment by hammacktony** [comment]
Yeah...that is what I was thinking. Pretty simple
