### ISSUE TITLE
Masonite not handling japanese characters well

### ISSUE THREAD

**Issue by josephmancuso** [MasoniteFramework/core#624]
if you paste japanese characters into a template, the content length will be off.

片仮名

**Comment by kentaro0919** [comment]
[Flask](https://github.com/pallets/flask/search?q=Content-Length&unscoped_q=Content-Length) uses the file size, not the data size.

**Comment by josephmancuso** [comment]
gonna need help on this one .. the issue with file size is Masonite doesn't create files it only uses Jinja's default rendering.

Maybe jinja has an option for this?

**Comment by josephmancuso** [comment]
#639 fixes this. I found out that if I convert to bytes and check the length I get the correct length
