### ISSUE TITLE
craft command command not adding "Command" at the end

### ISSUE THREAD

**Issue by kentaro0919** [MasoniteFramework/core#625]
In the document 
Make sure you instantiate the command. Also the command name needs to end in **"Command". ** So binding HelloCommand will work but binding Hello will not. Craft will only pick up commands that end in Command. This is also case sensitive so make sure Command is capitalized.

Other craft command add the respected end.  craft command should generate
craft command {name}
{name}Command.py by delault

**Comment by josephmancuso** [comment]
agreed
