### ISSUE TITLE
Add more built in view helpers

### ISSUE THREAD

**Issue by josephmancuso** [MasoniteFramework/core#646]
Need to add more view helpers. This is a list of what we currently have: https://docs.masoniteproject.com/the-basics/views#helpers

Thinking of things like:

- [ ] `sign()` - signs a string using the apps secret key. Same as `masonite.auth.Sign().sign()`
- [ ] `encrypt()` same as above. just an alias
- [ ] `unsign()` - signs a string using the apps secret key. Same as `masonite.auth.Sign().unsign()`
- [ ] `decrypt` - same as above. just an alias
- [ ] `url()` - used to get the full url path of the application: `url('dashboard')` is `http://example.com/dashboard`. This should be similar as the `request.route(full=True)` thingy
- [ ]  `config()` this is same as `masonite.helpers.config`
- [ ] `optional()` same as `masonite.helpers.optional`
- [ ] `dd()` same as the normal `dd()`
- [ ] `cookie()` same as `masonite.request.Request.get_cookie()`

**Comment by Marlysson** [comment]
All of this is just a shortcut to use within views?

**Comment by josephmancuso** [comment]
@Marlysson yes
