### ISSUE TITLE
uploading a pdf does not seem to work

### ISSUE THREAD

**Issue by josephmancuso** [MasoniteFramework/core#648]

**Comment by kentaro0919** [comment]
uploading a CSV is not working as well

**Comment by josephmancuso** [comment]
also was unable to reproduce. The above code snippet works

**Comment by josephmancuso** [comment]
just as a note, the reason for this is that most uploads will want to upload images. If you want to upload  more insecure mediums like .exe files, you need to make a concious decision to upload in these formats by explicitly coding the file extensions.

Just a security measure
