### ISSUE TITLE
add a collect helper

### ISSUE THREAD

**Issue by josephmancuso** [MasoniteFramework/core#652]
Orator has a collection but it's not very obvious how to do it. We should be able to do something like:

```python
from masonite.helpers import collect

def show(self ..)
    collection = collect([1,2,3,4])
    collection.chunk(2)
```

**Comment by danieldsf** [comment]
Hey @josephmancuso do you suggest the developers to create a class to manage collections implementing all the methods that Laravel does in here? https://laravel.com/docs/5.8/collections

**Comment by josephmancuso** [comment]
no orator already has one that does all that. It really just involved making this a wrapper around that.

might even just be doing:

```
# Masonite helper file
from backpack import Collection

collect = Collection
```

Something like . that? idk what the import actually is. Will need to do research on it.

**Comment by danieldsf** [comment]
I see. Thank you!
