### ISSUE TITLE
create code for redirecting back to the previous page

### ISSUE THREAD

**Issue by josephmancuso** [MasoniteFramework/core#67]
A lot of the time you will need to redirect to a different page and quickly redirect back.

For example you may want the user to login but then go right back to the page they were at.

right now the solution is something like:

* set an parameter in the url:

`domain.com/login?back=/user/1`

and then catching that in the show controller:

```python
def show(self):
    if request().has('back'):
        request().session.set('back', request().input('back'))
```

and then inside the store controller (or wherever you are processing the form)

```python
def store(self):
    if request().session.has('back'):
        return request().redirect(request().session.get('back'))
```

I'm wondering if there is a shorter way to do this.

**Comment by josephmancuso** [comment]
there may be no obvious faster way without adding a bunch of unneeded code and making the code base more complex so if no-one things of a better way then we can close this issue. 

I just feel like there are too many steps here

**Comment by mapeveri** [comment]
I'm going to do this :)

**Comment by josephmancuso** [comment]
sounds good :) Let me know your thoughts on how we should get this down and go back to a specific route

**Comment by josephmancuso** [comment]
The idea here is if we go to a dashboard link but get redirected back to a login, how can we simply login and automatically go to the dashboard?

This should be really straight forward to implement in a project but not be too magical that it happens automatically.

**Comment by josephmancuso** [comment]
we might be able to use cookies for this

**Comment by josephmancuso** [comment]
yeah that would work. The only problem I am seeing is that when the user sends a POST request, you can no longer get that input from the query_string.

what you could do is check if it's there when you land on the login page and store as a cookie or flash the data possibly.

**Comment by josephmancuso** [comment]
I think a cool way to do this would be something like:

```python
def store(self):

    return request().back(default='/home')
```

which could will redirect exactly like you explained above but if there is no back redirection, redirect to the default url

**Comment by mapeveri** [comment]
I think this should be transparent to the user in the controller. Let me think about it a bit more.

**Comment by mapeveri** [comment]
@josephmancuso I was thinking about this, first of all there is some kind of login_required? Because if there is, we can put the cookie there for the 'url back' and then in the login, make a redirect if that cookie exists. What do you think?.  I think 'url_back' should only work with authentication.

**Comment by josephmancuso** [comment]
no if I understand your question correctly then there is no `login_required` anywhere.

What I'm thinking here is we can set a cookie of `redirect` or something. This needs to be inside the AuthenticationMiddleware though so look into the `MasoniteFramework/masonite` repo and make changes there. It comes with any application so just a new application and make appropriate changes.

This may look something like:

```python
...
    def before(self):
        ''' Run This Middleware Before The Route Executes '''
        if not self.request.user():

            # save the current path as a cookie
            self.request.cookie('redirect', self.request.path)

            self.request.redirectTo('login')
``` 

Then in our controller we can do:

```python
def show(self):
    return request().back(default='/home')
```

the back method might look something like:

```python
def back(self, default=None):
    if self.get_cookie('redirect'):
        return self.compile_route_to_url(self.cookie('redirect'))
    
    return self.compile_route_to_url(default)
```

Something like that. does that make sense?

**Comment by mapeveri** [comment]
Yes, but I would like it to be super transparent for the user. If I go to a page that needs authentication, it redirects me to the login, it would have to be like "example.com/login?redirect_url=user/profile", then after logging in directly to "example.com/user/profile", but transparent to the user, you do not have to put code in the controller. I explain more or less?

**Comment by mapeveri** [comment]
Me too! It's what I wanted.

**Comment by aisola** [comment]
Great! Yeah, it's a very straight forward solution to the problem. That's honestly what I like most about it.
