### ISSUE TITLE
Reconsider how testing works

### ISSUE THREAD

**Issue by josephmancuso** [MasoniteFramework/core#670]
We need to take a nice hard look into testing and make it so simple that it would be easier to use it than not. 

This issue will contain all thoughts on testing.

* We need to use a better testing library like `unittest`. `pytest` is ok but `unittest` has a lot more features we can use to our benefit.

* it will be easier to make all core tests unittest than build 2 seperate testing frameworks. The testcases for a Masonite application can be the same for core.

* We need a way to setup and teardown test databases.

* we need a way to run tests in a package without needing to create a crap ton of extra files. You can see some Masonite packages are bascially a full framework just to get integration tests done. This shouldn't be the case. Even core is a Masonite application. I should be able to test Masonite aspects. Maybe removing chunks of application code from core is a good way to show that we can integrate with a masonite app outside of the framework.

Maybe a testcase for databases looks something like:

```python
from masonite.testing import TestCase

class SomeTestCase(TestCase):

    def setUp(self):
        self.routes(..)
        self.database('testing', migrate=True, preserve=False)

    ...
```

or

```python
from masonite.testing import TestCase

class SomeTestCase(TestCase):

    def test_user_creates(self):
        with self.database(UserModel) as User:
            ## Everything inside here connects to the test database.
            User.create({..})

    ...
```

**Comment by nioperas06** [comment]
"we need a way to run tests in a package without needing to create a crap ton of extra files" 👍

**Comment by josephmancuso** [comment]
Accidentally pushed to the wrong branch but now we can setup database tests a lot easier now.

For example, we can now setup and teardown databases. Take a simple database test case:

```python
class TestDatabase(DatabaseTestCase):

    def setUp(self):
        super().setUp()
        self.make(User, self.users_factory, 20)

    def users_factory(self, faker):
        return {
            'name': faker.name(),
            'email': faker.email(),
            'password': '$2b$12$WMgb5Re1NqUr.uSRfQmPQeeGWudk/8/aNbVMpD1dR.Et83vfL8WAu',  # == 'secret'
        }
    def test_has_records(self):
        self.assertGreater(User.all().count(), 0)
```

Notice we can now seed the databases. The parent setup and teardown methods migrate and tear down the database inside the parent class.

We can override that behavior obviously by overriding the method but this is a basic way to test a database now.

**Comment by josephmancuso** [comment]
Also by default it will only use a sqlite database to prevent issues with a real database. You can override that behavior as well by changing a class attribute. All this will soon be documented by thats the general idea

**Comment by Marlysson** [comment]
1. What do you think about encapsulate the factory responsible to return the data basis to each object?
2. And "avoid" the calling of ```super().setUp()``` on each test..

E.g:

```python
class TestDatabase(DatabaseTestCase):
    def setUp(self):
        self.make(User, 20)
```

**Comment by josephmancuso** [comment]
the reason you call the parent class is a few reasons:

1. The parent `DatabaseTestCase` is responsible for setting some class level attributes like `self.factory` object.
2. the setup method is responsible for setting up the database (migrating) and the teardown is for resetting the database.

So the code snippet above would not set the database up and it's doing more than just calling the factory
