### ISSUE TITLE
Add sentry integration

### ISSUE THREAD

**Issue by josephmancuso** [MasoniteFramework/core#671]
Need a way to add sentry easily to the application

**Comment by hammacktony** [comment]
Isn't this already done with exception hooks?

**Comment by josephmancuso** [comment]
yeah but it would be cool if we added the class to enable it

**Comment by vaibhavmule** [comment]
Also, We can have support for Masonite in `sentry-sdk` 

https://github.com/getsentry/sentry-python/issues/378

**Comment by vaibhavmule** [comment]
something like this from `gbaleague`?

```
"""A Sentry Service Provider"""

from masonite.provider import ServiceProvider

class SentryExceptionHook:
    def load(self, container):
        from config import application
        if not application.DEBUG:
            import sentry_sdk
            sentry_sdk.init("https://5c97bd633c3144ef830895d92ffa7fa5@sentry.io/1470602")
            sentry_sdk.capture_exception()

class Sentry(ServiceProvider):
    """Provides Services To The Service Container"""

    wsgi = False

    def register(self):
        if not application.DEBUG:
            self.app.bind('SentryExceptionHook', SentryExceptionHook())
```

**Comment by josephmancuso** [comment]
i'm thinking we combine these with loggers somehow

a logger should have 2 methods, one to log messages and one that is called when an exception occurs.

This catches several usecases at once.

**Comment by hammacktony** [comment]
So...`sentry_sdk.init(KEY)` actually starts the sentry process, and it will automatically (as best as it can) catch exceptions. Theoretically, you can put it in `wsgi.py` and call it a day. `.capture_exception()` is a bit redundant.

**Comment by hammacktony** [comment]
I think the old `raven` sdk had a bit more firepower, but `sentry_sdk` is way more simplistic.

**Comment by vaibhavmule** [comment]
@hammacktony good catch, `.capture_exception()` is not required in our case.
