### ISSUE TITLE
Add changes to request.route() method

### ISSUE THREAD

**Issue by josephmancuso** [MasoniteFramework/core#682]
Right now if we go to a route like:

```python
Get('/dashboard/@site/deployments', 'SomeController@show').name('dashboard.show')
```

and then we need to add a named route in our templates:

```html
<a href="{{ route('dashboard.show', {'site': 1}) }}">
```

This seems a little repetitive .. We already have that dictionary inside the URL params like `request.param('site')`.

Since we already have that information, we SHOULD be able to exclude the extra parameters and it should update automatically for us like this:

```html
<a href="{{ route('dashboard.show') }}">
```

**Comment by nioperas06** [comment]
I like it!
