### ISSUE TITLE
add a way to call "no argument methods" on certain classes

### ISSUE THREAD

**Issue by josephmancuso** [MasoniteFramework/core#688]
Some classed have this setter method that does something like:

```python
mail.to('user@example.com').queue().send('hey!')
```

Notice the setter `queue()` method here. I wonder if we can do something like this instead:

```python
mail.to('user@example.com').queue.send('hey!')
```

It's a tiny bit cleaner and i am wondering if it is even possible ..

what might have to be does is adding a `__getattr__` method and then see if the name equals a property (like `_queue`) and then toggle that to true and return the instance ..

**Comment by ar45** [comment]
can be implemented by setting `.queue` as a descriptor.

```python
class Queue:
    def __get__(self, instance, owner=None):
        if instance:
            instance._queue = True
            return instance
        return self
    
class Mail:
    _queue = False
    queue = Queue()
```

**Comment by josephmancuso** [comment]
the more I think about this the more i think it's not really needed ..
