### ISSUE TITLE
Allow raise if any errors on new validation

### ISSUE THREAD

**Issue by rfschubert** [MasoniteFramework/core#691]
Currently, the new validation will return those errors, sometimes we may expect a Raise of every error.

Maybe we can add as a parameter as it is expected behavior.

```python
.validation(
    required(['email'])
    length(['age'], min=12, max=24)
    raise_if_any_fails=True
)
``` 

Then it raises a `ValueError` with the specific message error for the field with issue

**Comment by josephmancuso** [comment]
this is done so far
