### ISSUE TITLE
Controllers need to inherit from a Masonite base controller

### ISSUE THREAD

**Issue by josephmancuso** [MasoniteFramework/core#695]
We need to have a way to add features to controllers in 2.2 so we need to inherit from a base controller **even if there are no methods involved on it**

**Comment by vaibhavmule** [comment]
features like?

**Comment by josephmancuso** [comment]
thinking eventually it will have something like:

```
class SomeController(Controller):

    def __init__(self):
        self.middleware('auth', 'custom')
```

as our first feature

**Comment by vaibhavmule** [comment]
I like it, it opens up a lot of possibilities.
