### ISSUE TITLE
Add Rule Enclosures

### ISSUE THREAD

**Issue by josephmancuso** [MasoniteFramework/core#697]
Need to add Rule Enclosures

"Rule Enclosures" (or some other name)

Basically an abstracted class that contains specific and reusable rules:

```python
class AcceptedTerms:

    def handle(self):
        return [
            accepted('terms'), greater_than('age', 18)
        ]

class ValidDomains:

    def handle(self):
        return [
            active_domain(['domain', 'email'])
        ]
```

and then use them in your controllers:

```python
def show(self, request: Request):
    errors = request.validate(
        AcceptedTerms, ValidDomains
    )
```

**Comment by Marlysson** [comment]
Great, will then the framework provide to developer some validators encapsulated into classes?

Does the developer using the framework don't would be able to create them abstracting common validators?

**Comment by josephmancuso** [comment]
yup you would be able to abstract all the rules

**Comment by Marlysson** [comment]
Yep, but giving a set of rules together into classes or give the possibility to developer to do this?

**Comment by josephmancuso** [comment]
The developer would make their own classes. Masonite would not provide any out of the box

**Comment by Marlysson** [comment]
There are something to do related to this class into Masonite's core code?

**Comment by josephmancuso** [comment]
yeah this hasn't been started yet. I'll knock it out this weekend though once I have free time since the validation stuff is not on develop branch so branching from a branch as a PR may get messy

**Comment by josephmancuso** [comment]
this is done

https://docs.masoniteproject.com/v/v2.2/advanced/validation#rule-enclosures
