### ISSUE TITLE
craft upgrade command

### ISSUE THREAD

**Issue by vaibhavmule** [MasoniteFramework/core#705]
`craft upgrade` a command that upgrades `masonite` and `masonite-cli` packages. 

it calls `pip install -U masonite masonite-cli` when the command is triggered.

**Comment by josephmancuso** [comment]
hmm what about for those that use pipenv or poetry?

**Comment by vaibhavmule** [comment]
I haven't thought through this, I might add `craft upgrade --pkg=pipenv` but then I would just do `pip install -U masonite` 

closing this for now till we settle down to use pipenv or poetry by default!
