### ISSUE TITLE
optimize: Move compiling of routes when the server first boots

### ISSUE THREAD

**Issue by josephmancuso** [MasoniteFramework/core#720]
This line of code runs on every request and takes a few milliseconds to run. There should be a way to move this into maybe when the route itself is instantiated. Maybe add a new attribute on the route called `_compiled_url` which already has the compiled url instead of compiling on each request

https://github.com/MasoniteFramework/core/blob/2.1/masonite/providers/RouteProvider.py#L27

**Comment by hammacktony** [comment]
Look into `functools.lrucache`. A simple caching decorator might do the job. Many frameworks I see do that.

**Comment by josephmancuso** [comment]
moving it before the server starts would be the same as caching it

**Comment by hammacktony** [comment]
I know....but one is simpler.

**Comment by josephmancuso** [comment]
simpler than setting an attribute on a class?

**Comment by hammacktony** [comment]
I am not afraid to move it to start time, but this is a simple fix.

**Comment by josephmancuso** [comment]
oh i see what you are saying. Yeah this fix was pretty simple tho

**Comment by hammacktony** [comment]
You would just do 
```
@functools.lrucache
def create_matchurl:
    return stuff
```

Route compiling is a 1-1 process...so it would work as it is supposed to.

**Comment by josephmancuso** [comment]
https://github.com/MasoniteFramework/core/pull/721

**Comment by hammacktony** [comment]
You might still want to use the cache. Just experiment.

Any 1-1 function that gets called alot can be cached with LRU Cache.

**Comment by josephmancuso** [comment]
yes i'll test it out. When things are saving milliseconds its hard to really measure on a requests per second basis. The profiler helps a lot tho
