### ISSUE TITLE
Makefile

### ISSUE THREAD

**Issue by hammacktony** [MasoniteFramework/core#730]
I think having a Makefile would be beneficial. It can help devs lint and test (because we all know remembering those commands are hard). Also, `make` is on almost every operating system. It is a standardized way of manipulating projects.

It should,

- Clean Project (remove `__pycache__/` and other useless decorrectories) `make clean`
- Lint with Flake8 `make lint`
- Test with Pytest `make test`
- Install application. Instead of downloading `masonite-cli` and then running `craft install`, have `make install` cover any initial project dependencies

If there are any other commands which might be useful, comment below.

**Comment by hammacktony** [comment]
Extends #617

**Comment by josephmancuso** [comment]
sounds good to me

**Comment by vaibhavmule** [comment]
This is done.
