### ISSUE TITLE
Pull request standardization

### ISSUE THREAD

**Issue by hammacktony** [MasoniteFramework/core#732]
We should standardize the pull request process. 

All pull requests should follow `<type>/<github issue number>-<tiny description>`.

- `<type>` refers to the overall type of pull request. (i.e `fix`, `hotfix`, `patch`, `feature`)
- `<github issue number>` Every pull request should reference an issue so that it is easy to understand what the pull request is used for.
- `-<tiny description>` is an optional description of what that pull request is. If an issue has bullet points, you could have multiple people working on the same issue. The description helps designate which bullet point refers to a pull request.

**Comment by josephmancuso** [comment]
Whats the best way to enforce this? just add this to contributing guide?

**Comment by josephmancuso** [comment]
https://github.blog/2016-02-17-issue-and-pull-request-templates/

**Comment by josephmancuso** [comment]
Can make templates inside the Insights > Community tab

**Comment by josephmancuso** [comment]
updated contributing guide
