### ISSUE TITLE
Drop Python 3.4 support for Masonite 2.2

### ISSUE THREAD

**Issue by vaibhavmule** [MasoniteFramework/core#736]
end-of-life for Python 3.4 is March 2019 and it will stop getting security fixes. 

I suggest only support 3.5, 3.6, 3.7 for Masonite 2.2.

**Comment by josephmancuso** [comment]
I'd like to support the last 4 python versions. Sort of been saying that for a while so would be weird to change now. Next release will break 3.4 support for sure
