### ISSUE TITLE
add better module controllers

### ISSUE THREAD

**Issue by josephmancuso** [MasoniteFramework/core#74]
@mapeveri Thoughts?

currently there is this:

```python
get('/url/here', 'Controller@method')
```

which will look for: `app.http.controllers.Controller.py`

Good so far.

Now in order to do a controller from say a `billing` module:
```python
get('/url/here', 'Controller@method').module('billing.controllers')
```

this will look for a controller in `billing.controllers.Controller.py`

This seems a little weird to me. I think we should do something like:

```python
get('/url/here', '\billing.controllers.Controller@method')
```

All this will do in the backend is check if the string starts with a backslash and get the controller accordingly. This logic is in the Route class.

If we go this route I say we remove the module method completely.

**Comment by josephmancuso** [comment]
For example all the controllers default to the app.http.controllers directory. Sometimes you might want to specify another directory (module) that contains controllers or even use third party controllers. I'm wondering if the backslash is a good approach to sort of symbolize  a new module location. We can use the module method like above but I'd like a super fast shorthand

**Comment by mapeveri** [comment]
For me I would have to search all the modules, without specifying anything, but if you like the backslash approach, I do not see it badly either.

**Comment by josephmancuso** [comment]
So you're saying search all of the installed modules for a match?

**Comment by mapeveri** [comment]
Yes, by default used controller folder, if this route not matched then search in other modules.

**Comment by josephmancuso** [comment]
Hmm that's actually really interesting. The problem would be though that you would have to check in every folder of every directory and it would also have to check in all of the pip installed folders and directories so you would increase the time it takes for your server to boot up the more dependencies have by sometimes an order of magnitude depending on the dependency.

**Comment by josephmancuso** [comment]
If there is a backslash (or something else like a ..) then we can just strip it out and locate it.

**Comment by mapeveri** [comment]
First would be the folder controller and then the modules registers, which could be in the configuration file, not all the pip modules. It's just an idea :)

**Comment by josephmancuso** [comment]
Hm that's tempting. I'll think about that actually. I'll be doing a good amount of dev work. Almost done billing the Masonite Billing package

**Comment by mapeveri** [comment]
Great, Anything that can i help, you tell me

**Comment by josephmancuso** [comment]
@mapeveri holy crap! After running some tests, apparently you can start the controller string with a forward slash and it will look for the controller globally:

```python
Get().route('test/url', '/app.http.controllers.TestController@show')
```

I accidentally found this feature lol

**Comment by josephmancuso** [comment]
nvm. false alarm

**Comment by josephmancuso** [comment]
so for future reference, the backslash didn't work. Whenever you put a backslash it acts as an escape and even though it will work fine it makes the letter right after it a different color because of text editors. This would get annoying so now it's a forward slash
