### ISSUE TITLE
Dependabot

### ISSUE THREAD

**Issue by hammacktony** [MasoniteFramework/core#742]
Look into dependabot for dependency updates.

https://dependabot.com/

**Comment by vaibhavmule** [comment]
@josephmancuso I have requested the addition of `dependabot`.

**Comment by josephmancuso** [comment]
this just updates the requirements.txt?

**Comment by hammacktony** [comment]
Yep

**Comment by josephmancuso** [comment]
But all dependencies are based on version ranges so what would it upgrade?

**Comment by vaibhavmule** [comment]
Which all dependancies? https://github.com/MasoniteFramework/core/blob/2.1/requirements.txt these are not in range?

**Comment by josephmancuso** [comment]
i dont think this is really helpful unless it automatically does this for the setup.py file or something
