### ISSUE TITLE
move masonite application to folder

### ISSUE THREAD

**Issue by vaibhavmule** [MasoniteFramework/core#747]
Currently, we have `13 directories` on level 1 for `core` repo. If we remove the boilerplate code that we use for testing, it can be reduced to `5 directories`. As I have seen, our tests, mostly use config files.

can we move that boilerplate to `tests/project` and then import from there.

if we do that, this is how `core` repo will look like.
```
├── CHANGELOG.md
├── CODE_OF_CONDUCT.md
├── CONTRIBUTING.md
├── LICENSE
├── MANIFEST.in
├── Pipfile
├── README.md
├── __pycache__
├── craft
├── masonite
├── masonite.db
├── pytest.ini
├── requirements.txt
├── setup.cfg
├── setup.py
├── testpackage
├── tests
├── uploads
└── wsgi.py

5 directories, 14 files
```

**Comment by hammacktony** [comment]
I would welcome with this change.
