### ISSUE TITLE
Explicit Python3 and Pip3 in Makefile

### ISSUE THREAD

**Issue by hammacktony** [MasoniteFramework/core#767]
Just looked at the Makefile and realized something: all the python and pip commands are of the python 2 and pip 2 convention. Due to some weirdness in the Python community, `python` and `pip` are not `python3` and `pip3`. For instance, MacOS' default python installation is 2.7.

Solution: replace all instances of `python` and `pip` with `python3` and `pip3`.

**Comment by vaibhavmule** [comment]
Those commands are made into consideration that you have enabled a virtual environment for Python 3.

**Comment by hammacktony** [comment]
Not all people use virtual environments. Once again, my coworkers are not that fond of them. There are also people who don't know to use a virtual environment.

**Comment by josephmancuso** [comment]
This would really only be for Masonite core development / contributing. Not all people use Masonite but also not all application use `python3` aliases. It depends on how you installed Python. 

So the solution here is really to be inside a virtual environment to use the command. either solution will break for some people. It'll either break for those who don't use virtual env or break for those who don't have the python3 alias
