### ISSUE TITLE
Move authentication controllers into `app/http/controllers/auth`

### ISSUE THREAD

**Issue by nioperas06** [MasoniteFramework/core#777]
Move authentication controllers into `app/http/controllers/auth` when running `craft auth`.

**Comment by nioperas06** [comment]
Can I make authentication templates look like Laravel one? Taking this too #775

**Comment by josephmancuso** [comment]
how do you mean?

**Comment by nioperas06** [comment]
![Register pages](https://user-images.githubusercontent.com/11293401/62001360-94631980-b0e6-11e9-8711-3ef3ca490f68.png)

**Comment by josephmancuso** [comment]
oh yeah sure

**Comment by vaibhavmule** [comment]
Note to me: Need to update the description to clear instruction to fix this issue.

**Comment by apoos-maximus** [comment]
i have picked up this issue

**Comment by vaibhavmule** [comment]
@apoos-maximus Sure, let me know if you need to know more.

**Comment by gdhameeja** [comment]
Is this still available? I can work on it.

**Comment by josephmancuso** [comment]
Yes it’s still available

**Comment by gdhameeja** [comment]
So, I was looking into the code, and it seems that currently the auth controllers are created in app/http/controllers/, but according to the issue we need to create an extra directory in between with the name 'auth'? I made the change in AuthCommand: https://github.com/MasoniteFramework/core/compare/2.2...gdhameeja:fix-777

Also how do I test this? I couldn't find any tests for this command.
This is my first PR to open source. I apologize in advance for any mistakes. Thanks

**Comment by vaibhavmule** [comment]
@gdhameeja 

Thanks for the PR, @josephmancuso  or me will have look at your PR very soon. 

And, We welcome new contributors and not need to apologize.

The way to test this is that auth controller files are generated when you run `craft auth`.

if you try running this command and let us know if you are able to test it or not.
