### ISSUE TITLE
Custom masonite craft command with multiple options or params

### ISSUE THREAD

**Issue by holic-cl** [MasoniteFramework/core#783]
Hi,

I was wonder how to add multiple options on a custom craft command. I tried this:

    """
    Call to dump-ddb system command

    dump-ddb
        {ddb_path : Path to ddb file}
        {param : Parameter}
        {argument : Argument}
    """

But with not success. Besides i don't know how to create optional arguments or params. Is there way to accomplish that?

Regards

**Comment by vaibhavmule** [comment]
you just need to add `?` at the end of argument like this `argument?`.

more info check cleo which is used in `core` of `masonite`docs: https://github.com/sdispater/cleo#usage
