### ISSUE TITLE
craft package file structure

### ISSUE THREAD

**Issue by nioperas06** [MasoniteFramework/core#784]
```bash
craft package test
```
This will create:
```
[+] test
  [+] test
      - __init__.py
      - integration.py
  - MANIFEST.in
  - setup.py
```
Do we really need the first top-level folder?

**Comment by vaibhavmule** [comment]
Can you please elaborate that how it's helps in creating tests?

**Comment by josephmancuso** [comment]
the craft package command needs to be revamped. I dont use it because its not good enough and thats an issue lol

**Comment by nioperas06** [comment]
@vaibhavmule I think that `craft package` command should create something like below:
```bash
craft package testpackage
```
This will create:
```
[+] testpackage
    - __init__.py
    - integration.py
[+] tests
- MANIFEST.in
- setup.py
```
 Still struggling with package creation  @josephmancuso  😞

**Comment by josephmancuso** [comment]
yeah that command is a little old school and not even really the best way to create a package anymore. Not even that file structure. If you take a look at some of the more recent packages I made i think it makes a lot more sense. Take a look at the selenium or validation package

**Comment by josephmancuso** [comment]
should now use this repo https://github.com/MasoniteFramework/starter-package
