### ISSUE TITLE
Add storage/uploads/ folder to gitignore

### ISSUE THREAD

**Issue by holic-cl** [MasoniteFramework/core#787]
**Is your feature request related to a problem? Please describe.**
When i want to upload files, my default idea is to upload to storage/uploads/ folder. When i make this my uploaded files (profile images, avatars, or any file i want to upload) will be tracked by git as every file on that folder.

**What do we currently have to do now?** 
I think is good idea to add a .gitkeep file on `storage/uploads/` folder but avoid to git to add those files to the repository.

**Describe the solution you'd like**
Avoid to git to file tracking of site uploaded files as avatars, profile pictures, etc.

**Describe alternatives you've considered**
Add folder to masonite structure but add files inside of that folder to gitignore file

**Comment by vaibhavmule** [comment]
.gitignore file: https://github.com/MasoniteFramework/core/blob/2.2/.gitignore

**Comment by josephmancuso** [comment]
Simply add the line `storage/uploads` to this file https://github.com/MasoniteFramework/masonite/blob/2.2/.gitignore

**Comment by TRSridhar** [comment]
I am working on this

**Comment by vaibhavmule** [comment]
@TRSridhar Sure.
