### ISSUE TITLE
Validation.when not behaving as expected.  

### ISSUE THREAD

**Issue by JacksonToomey** [MasoniteFramework/core#799]
**Describe the bug**
When using validation.when, the when clause seems to always be validated against.

**To Reproduce**
Using the validation
`request.validate(
    validation.when(
        validation.isnt(validation.exists('email')),
    ).then(
        validation.required('phone_number'),
    )
)`
with the input `{'phone_number': '', 'email': 'demo@email.com', 'password': '', 'name': ''}` returns an error dictionary of `{'email': ['email is not required']}`.

**Expected behavior**
The input `{'phone_number': '', 'email': 'demo@email.com', 'password': '', 'name': ''}` should be valid.

**Comment by josephmancuso** [comment]
I think I got the fix for that. let me just package a real together

**Comment by josephmancuso** [comment]
fixed. Update masonite and should get the latest version of masonite validations.

If not you can do `pip install masonite-validations>2.2`
