### ISSUE TITLE
[Error] Destination path '' already exists

### ISSUE THREAD

**Issue by vaibhavmule** [MasoniteFramework/core#812]
```
[Error] Destination path '/Users/vaibhavmule/Dropbox/work/foo/LICENSE' already exists
```
I try adding masonite project to my current directory where `LICENSE` already exists. 

What I suggest here is to delete the existing file and add a new one, that way I can see git diff and make a decision based on that.

**Comment by josephmancuso** [comment]
what if its not a git repo yet?

**Comment by vaibhavmule** [comment]
we can `-f` like mode?

**Comment by josephmancuso** [comment]
ummm not really a fan. If this becomes a bigger issue we can reopen
