### ISSUE TITLE
remove commented out code

### ISSUE THREAD

**Issue by vaibhavmule** [MasoniteFramework/core#843]
remove the comments from this lines https://github.com/MasoniteFramework/core/blob/2.2/masonite/view.py#L191,L192

Change this
```
"""        # loader(package_name, location)
# /dashboard/templates/dashboard
```
to this, make you sure you do not delete that ending three quotes.
```
"""
```

**Comment by Dsujan** [comment]
Added a PR. :)

**Comment by Dsujan** [comment]
https://github.com/MasoniteFramework/core/pull/847
@vaibhavmule  PR  has been approved. You can close the issue now.
