### ISSUE TITLE
old helper function

### ISSUE THREAD

**Issue by nioperas06** [MasoniteFramework/core#845]
Useful for re-populating forms after detecting validation errors.

**Comment by Marlysson** [comment]
There're more description about this feature @nioperas06 ?

**Comment by nioperas06** [comment]
![Mockup](https://user-images.githubusercontent.com/11293401/62088057-deb9d700-b25b-11e9-83d0-2ef4908f390b.png)

Let's build a simple form and submit it with a wrong password. For UX purposes, we want to re-populate fields (like name or email). Now, you can achieve that like below:
```python
request.session.flash('name', request.input('name', ''))
```

```html
<input name="name" type="text" value="{% if session().has('name') %}{{ session().get('name') }}{% endif %}">
```

Laravel provides a simple [helper](https://laravel.com/docs/5.8/helpers#method-old) to retrievie an old input value flashed into the session.
So, we can do something like this:

```html
<input name="name" type="text" value="{{ old('name') }}">
```
Well explained @Marlysson 😄  ?

**Comment by Marlysson** [comment]
Very well explained @nioperas06 . I'll see how can build this help to solve this issue.

**Comment by Marlysson** [comment]
@nioperas06 
When you show this snippet to recover the default input submitted:

```python
request.session.flash('name', request.input('name', ''))
```

I was analysing the `Request` class and there are the `input` method:

```python
 input(self, name, default=False, clean=True):
```
What if the ```clean``` was defined to `False` during the validation in controller, would the view yet need to use this?

```python
{% if session().has('name') %}{{ session().get('name') }
```

**Comment by Marlysson** [comment]
To propose of implementation, the `old helper` just would use the request class with clean parameter defined to `False`?

Or would use the session.flash verifying whether there is the key like input's name of form...

**Comment by josephmancuso** [comment]
`request.session.flash('name', request.input('name', ''))` defaults the value to a blank string. Nothing to do with cleaning it.

What cleaning does is prevents things like script tags being sent and helps protect against things like SQL injection. The input should really only **not** be cleaned if you know what you are doing and should not be defaulted to `False`

**Comment by Marlysson** [comment]
@josephmancuso Does the data in session avoid SQL injection, they are already validated?

**Comment by josephmancuso** [comment]
Orator itself protects against sequel injection if you are not using any raw queries. 

All this helper is doing is printing the string back out. We will only use this helper when redirecting back to a form because of some validation error
