### ISSUE TITLE
Remove unnecessary comment from KeyCommand.py

### ISSUE THREAD

**Issue by vaibhavmule** [MasoniteFramework/core#851]
Just remove comments from following lines
20, 23 and 29
https://github.com/MasoniteFramework/core/blob/2.2/masonite/commands/KeyCommand.py#L20
https://github.com/MasoniteFramework/core/blob/2.2/masonite/commands/KeyCommand.py#L23
https://github.com/MasoniteFramework/core/blob/2.2/masonite/commands/KeyCommand.py#L29

**Comment by TRSridhar** [comment]
I have created a pull request for #857 Please review. 
https://github.com/MasoniteFramework/core/issues/851
