### ISSUE TITLE
remove unnecessary comment from routes.py

### ISSUE THREAD

**Issue by vaibhavmule** [MasoniteFramework/core#854]
remove line from https://github.com/MasoniteFramework/core/blob/2.2/masonite/helpers/routes.py#L17

**Comment by prashant0493** [comment]
@vaibhavmule I have solved this issue here - https://github.com/MasoniteFramework/core/pull/859
can you please take a look?

**Comment by vaibhavmule** [comment]
@prashant0493 
Thanks for PR. I will check and merge.
