### ISSUE TITLE
Readability and optimisation by merging multiple isinstance calls - DeepSource suggested

### ISSUE THREAD

**Issue by TRSridhar** [MasoniteFramework/core#866]
Merging of multiple isinstance calls to isinstance(self.data(), (dict, list))
It is recommended to merge multiple consecutive isinstance calls into one for better readability.

File: masonite/response.py
https://github.com/MasoniteFramework/core/blob/develop/masonite/response.py#L69-L69
Consider merging these isinstance calls to isinstance(self.data(), (dict, list))
https://github.com/MasoniteFramework/core/blob/develop/masonite/response.py#L92-L92
Consider merging these isinstance calls to isinstance(view, (dict, list))
https://github.com/MasoniteFramework/core/blob/develop/masonite/response.py#L94-L94
Consider merging these isinstance calls to isinstance(view, (Collection, Model))

**Comment by shallow-source** [comment]
Fixed this at
https://github.com/shallow-source/core/blob/develop/masonite/response.py#L69-L69
