### ISSUE TITLE
Usage f-strings in Next Major 3.8

### ISSUE THREAD

**Issue by vaibhavmule** [MasoniteFramework/core#878]
We are dropping support for Python 3.4 in #877 and f-strings has introduced in 3.5 and we should use f-string wherever needed in favor of `.format()` or operator based formating.

**Comment by josephmancuso** [comment]
Yup Agreed. We can now do a lot of things with the develop branch now that 3.4 will not be supported anymore

**Comment by josephmancuso** [comment]
F strings are actually 3.6 + and we still need to support 3.5

**Comment by vaibhavmule** [comment]
Oops, I always believed, they are in 3.5. Thanks, you pointed out.

**Comment by josephmancuso** [comment]
yes I forgot too until i looked it up lol
