### ISSUE TITLE
Merge Masonite API package into main application.

### ISSUE THREAD

**Issue by josephmancuso** [MasoniteFramework/core#887]
Not sure if this is completely doable or the best choice but might be a good idea to merge the API package into core and make it more supported out of the box.

This may also be a good time to rework the whole thing.

It needs to be very powerful and easily extendable.

**Comment by josephmancuso** [comment]
Masonite does not have terribly good API support.

**Comment by garyburgmann** [comment]
Where did you land on this @josephmancuso? I know personally that I am most likely to spin up Masonite as an API. I think the use-case is high enough these days to call for it as part of core. 

That being said, if plug and play is as easy Django + Django Rest Framework, then it isn't the end of the world to keep it as a separate package.

**Comment by josephmancuso** [comment]
@garyburgmann its more for adding new features and maintaining the package. It's a bit harder to make sure nothing is breaking and trying to keep them both up to date with eachother is just more than its worth.

The only real thing we gain by making it a separate package is we make core a bit smaller but thats not a good benefit vs the downsides. It hasn't gotten many features because its more vestigial than a part of Masonite.

Also maybe the issue is that it's not really that easy to test packages with Masonite outside of a "Masonite App". Maybe more work in this area will make it better to keep it outside of core where it is now

**Comment by josephmancuso** [comment]
No longer going to do this. I really need to make sure packages are able to be fully tested outside of Masonite
