### ISSUE TITLE
Add a dashboard

### ISSUE THREAD

**Issue by josephmancuso** [MasoniteFramework/core#90]
This should live in it's own repository and should come with:

* a command to make a super user
* requires a new `is_admin` to the user model which requires the user to make a new migration
 (or we can add one by default if we are shipping this package by default)
    * if this does ship by default we can try to be done with it before the 1.6 release and release it with that or work on it slower and target the 2.0 release
* the dashboard that the user will use to control crud

I'm wondering if this should be a replica of the Django interface or if it should be unique and cool looking

**Comment by mapeveri** [comment]
I think I should have his unique touch, but influenced by Django.
