### ISSUE TITLE
Create route groups

### ISSUE THREAD

**Issue by josephmancuso** [MasoniteFramework/core#93]
Thought of something really cool. We can have route groups. Something like:

```python
from masonite.helpers.routes import group, get, post

ROUTES = [
    get('/some/url', 'Controller@show'),
    ....
    group('/dashboard', [
        get('/user', 'UserController@show'),  # returns '/dashboard/user'
        post('/user', 'UserController@store'),
        ...
    ])
]
```

The problem here is that this will have to be apart of the list. group will need to return a list but then you will end up with something like:

```python
[
    get(..),
    post(..)
    [
        get(..),
        post(..)
    ]
]
```

This obviously won't work because we need a single list. So what we could do is something like:

```python
from masonite.helpers.routes import group, get, post

ROUTES = [
    get('/some/url', 'Controller@show'),
    ....
    *group(prefix='/dashboard', [
        get('/user', 'UserController@show'), # returns '/dashboard/user'
        post('/user', 'UserController@store'),
        ...
    ])
]
```

(notice the star there which should unpack the list) But I think that's ugly and people are going to forget that

or can `group` could possibly return an unpacked list?

```python
def group(url, route_list):
    return *route_list # will this work? I think so
```

the group function will need something like:

```python
def group(prefix, route_list):
    # prepend the prefix ('/dashboard')
    for route in route_list:
        route.route_url = prefix + route.route_url # now '/dashboard/user'

    return *route_list
```

@mapeveri What do you think about this?

This can actually ship with Masonite 1.6.1

**Comment by mapeveri** [comment]
A user level, for me, I like this example:

```
from masonite.helpers.routes import group, get, post

ROUTES = [
    get('/some/url', 'Controller@show'),
    ....
    group('/dashboard', [
        get('/user', 'UserController@show'),  # returns '/dashboard/user'
        post('/user', 'UserController@store'),
        ...
    ])
]
```
This is very clear. 
Maybe in the group of functions, join the routes and return only one.?

**Comment by josephmancuso** [comment]
> Maybe in the group of functions, join the routes and return only one.

can you elaborate on that? I'm playing around with this feature now and apparently you cant `return *list` ..

**Comment by mapeveri** [comment]
Sure, when the list are like this:

```
[
    get(..),
    post(..)
    [
        get(..),
        post(..)
    ]
]
```

The function must return something like that:

```
[
    get(..),
    post(..)
    get(/dashboard/users...),
    post(/dashboard/users...)
]
```

**Comment by josephmancuso** [comment]
right which needs unpacking

**Comment by mapeveri** [comment]
Exactly!

**Comment by josephmancuso** [comment]
right so we sort of need a star somewhere although it's so small I feel like people will keep forgetting it

**Comment by josephmancuso** [comment]
I'd like it to be cleaner.

**Comment by mapeveri** [comment]
Why the star?

**Comment by josephmancuso** [comment]
because the list returned from group needs to be unpacked somewhere

**Comment by josephmancuso** [comment]
This is the code that is working now:

```python
def group(url, route_list):
    for route in route_list:
        route.route_url = url + route.route_url
    
    return route_list

ROUTES = [
    get('/', 'WelcomeController@show').name('home'),
    get('/discover', 'WelcomeController@discover').name('discover'),

    *group('/dashboard', [
        get('/user', 'WelcomeController@discover').name('discover'),
        get('/test', 'WelcomeController@discover').name('discover'),
    ]),
```

**Comment by josephmancuso** [comment]
but I feel like that's weird and ugly lol

**Comment by mapeveri** [comment]
Yes, but we can do it without the star, simply checking if it is a list. Or not?

**Comment by josephmancuso** [comment]
this is what we need:

```python
def group(url, route_list):
    for route in route_list:
        route.route_url = url + route.route_url
    
    return *route_list

ROUTES = [
    get('/', 'WelcomeController@show').name('home'),
    get('/discover', 'WelcomeController@discover').name('discover'),

    group('/dashboard', [
        get('/user', 'WelcomeController@discover').name('discover'),
        get('/test', 'WelcomeController@discover').name('discover'),
    ]),
```

**Comment by josephmancuso** [comment]
yeah that will require changes to the core code. I suppose it's worth checking into. I was hoping it would just be a simple function :(

**Comment by mapeveri** [comment]
Ahhh ok I understand! I think that is the best option.

**Comment by josephmancuso** [comment]
actually it might not be too hard .. this is in RouteProvider

```python
    def boot(self, WebRoutes, Route, Request, Environ, Headers):
        for route in WebRoutes: # WebRoutes needs to look like you showed above
```

**Comment by josephmancuso** [comment]
somewhere we need to make some logic to unpack all the values. It can even be right above the for loop

**Comment by josephmancuso** [comment]
I'm going out today so I won't be available but I'll take a swing at this tonight if you haven't started it
