### ISSUE TITLE
Validator should handle null values as empty

### ISSUE THREAD

**Issue by erikwestlund** [MasoniteFramework/core#939]
**Describe the bug**
If you validate an ajax request with null values, it throws this error:

ContainerError > expected string or bytes-like object 

If you submit just '' (empty string), no issues.

**To Reproduce**
1. Create an ajax form
2. Submit a null value
3. Try to validate that value

**Expected behavior**
Validator should coerce null to an empty string or gracefully handle null values.

**Comment by josephmancuso** [comment]
what is the vaidation rule(s) you tried validating with? I wrote a few tests and they seem to be passing

**Comment by josephmancuso** [comment]
Just did manual tests and it does look to be working. Will reopen if we can find more info
![Screen Shot 2019-11-24 at 9 27 01 PM](https://user-images.githubusercontent.com/20172538/69507627-33671900-0f01-11ea-8708-cc1cc8be23ef.png)
![Screen Shot 2019-11-24 at 9 26 45 PM](https://user-images.githubusercontent.com/20172538/69507629-33671900-0f01-11ea-8f47-36855d133d10.png)
